export const pllFrequencies = [
  { value: "x R' U R' D2 R U' R' D2 R2 x'", step: "pll", frequency: 28 },
  { value: "x' R2 D2 R' U' R D2 R' U R' x", step: "pll", frequency: 6 },
  { value: "R' D' R U' R' D R U' R' D' R U2 R' D R", step: "pll", frequency: 3 },
  { value: "R U R' F' r U R' U' r' F R2 U' R'", step: "pll", frequency: 3 },
  { value: "R' D' R U' R' D R U2 R' D' R U' R' D R", step: "pll", frequency: 2 },
  { value: "x R2 D2 R U R' D2 R U' R x'", step: "pll", frequency: 26 },
  { value: "x' R U' R D2 R' U R D2 R2 x", step: "pll", frequency: 12 },
  { value: "x L U' L D2 L' U L D2 L2 x'", step: "pll", frequency: 5 },
  { value: "R' D' R U2 R' D R U R' D' R U R' D R", step: "pll", frequency: 4 },
  { value: "l' R' D2 R U R' D2 R U' R", step: "pll", frequency: 2 },
  { value: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", step: "pll", frequency: 14 },
  { value: "R' U' R' D' R U' R' D R U R' D' R U R' D R2", step: "pll", frequency: 7 },
  { value: "R' U2 R' D' R U R' D R U' R' D' R U2 R' D R2", step: "pll", frequency: 1 },
  { value: "x' L' U L D' L' U' L D L' U' L D' L' U L D x", step: "pll", frequency: 1 },
  { value: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", step: "pll", frequency: 32 },
  { value: "R' F R f' R' F R2 U R' U' R' F' R2 U R' S", step: "pll", frequency: 2 },
  { value: "R' U R U' R2 F' U' F U R F R' F' R2", step: "pll", frequency: 1 },
  { value: "R2 U R' U R' U' R U' R2 D U' R' U R D'", step: "pll", frequency: 31 },
  { value: "D' R2 U R' U R' U' R U' R2 D U' R' U R", step: "pll", frequency: 1 },
  { value: "R2 u R' U R' U' R u' R2 F' U F", step: "pll", frequency: 1 },
  { value: "R U R' F' R U R' U' R' F R U' R' F R2 U' R' U' R U R' F'", step: "pll", frequency: 1 },
  { value: "R' U' R D' U R2 U R' U R U' R U' R2 D", step: "pll", frequency: 21 },
  { value: "F' U' F R2 u R' U R U' R u' R2", step: "pll", frequency: 17 },
  { value: "R' d' F R2 u R' U R U' R u' R2", step: "pll", frequency: 5 },
  { value: "D R' U' R D' U R2 U R' U R U' R U' R2", step: "pll", frequency: 1 },
  { value: "F' U' F R2 u R' U R U' E u U' R u' R2", step: "pll", frequency: 1 },
  { value: "R2 F2 R U2 R U2 R' F R U R' U' R' F R2", step: "pll", frequency: 25 },
  { value: "R2 U' R U' R U R' U R2 D' U R U' R' D", step: "pll", frequency: 11 },
  { value: "L2 U' L U' L U L' U L2 D' U L U' L' D", step: "pll", frequency: 3 },
  { value: "R2 F2 R U2 R U2 R' F R U R2 R U' R' F R2", step: "pll", frequency: 1 },
  { value: "R2 F2 R U2 R U2 U U' R' F R U R' U' R' F R2", step: "pll", frequency: 1 },
  { value: "R U R' D U' R2 U' R U' R' U R' U R2 D'", step: "pll", frequency: 27 },
  { value: "D' R U R' D U' R2 U' R U' R' U R' U R2", step: "pll", frequency: 6 },
  { value: "R U R' y' R2 u' R U' R' U R' u R2", step: "pll", frequency: 1 },
  { value: "M2 U M2 U2 M2 U M2", step: "pll", frequency: 16 },
  { value: "M2 U' M2 U2 M2 U' M2", step: "pll", frequency: 12 },
  { value: "M2 U2 M2 U M2 U2 M2", step: "pll", frequency: 2 },
  { value: "R' U L' U2 R U' R' U2 R L", step: "pll", frequency: 23 },
  { value: "L' U' L F L' U' L U L F' L2 U L", step: "pll", frequency: 14 },
  { value: "x R2 F R F' R U2 r' U r U2 x'", step: "pll", frequency: 7 },
  { value: "L' U R' U2 L U' L' U2 L R", step: "pll", frequency: 6 },
  { value: "L' U R' z R2 U R' U' R2 D", step: "pll", frequency: 2 },
  { value: "R U R' F' R U R' U' R' F R2 U' R'", step: "pll", frequency: 47 },
  { value: "R U R2 F' R U R U' R' F R U' R'", step: "pll", frequency: 2 },
  { value: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'", step: "pll", frequency: 18 },
  { value: "R' U R U' R' F' U' F R U R' F R' F' R U' R", step: "pll", frequency: 5 },
  { value: "R' U R U' R' F' U' F R U R' U' R U' f R f'", step: "pll", frequency: 4 },
  { value: "r' D' F r U' r' F' D r2 U r' U' r' F r F'", step: "pll", frequency: 3 },
  { value: "R' U L' U2 R U' L R' U L' U2 R U' r", step: "pll", frequency: 2 },
  { value: "R' U L' U2 l F' M' U L' U2 R U' L", step: "pll", frequency: 1 },
  { value: "R U' R' U' R U R D R' U' R D' R' U2 R'", step: "pll", frequency: 32 },
  { value: "R U' R' U' R U R' U R' D' R U' R' D R2 U R'", step: "pll", frequency: 7 },
  { value: "R U' R2 D' R U R' D R U' R U' R' U R U R'", step: "pll", frequency: 6 },
  { value: "R U R' F' R U2 R' U2 R' F R U R U2 R'", step: "pll", frequency: 3 },
  { value: "R' U2 R' D' R U' R' D R U R U' R' U' R", step: "pll", frequency: 20 },
  { value: "R' U2 R U2 R' F R U R' U' R' F' R2", step: "pll", frequency: 18 },
  { value: "R2 F R U R U' R' F' R U2 R' U2 R", step: "pll", frequency: 4 },
  { value: "R' U R U R' U' R' D' R U R' D R U2 R", step: "pll", frequency: 1 },
  { value: "R U R' U' R' F R2 U' R' U' R U R' F'", step: "pll", frequency: 42 },
  { value: "R U R' U' R' F R2 U' R' U F' L' U L", step: "pll", frequency: 7 },
  { value: "L' U' L U L F' L2 U L U L' U' L F", step: "pll", frequency: 1 },
  { value: "R U R' U R' U' R2 U' R' U R' U R", step: "pll", frequency: 27 },
  { value: "M2 U M U2 M' U M2", step: "pll", frequency: 18 },
  { value: "R U' R U R U R U' R' U' R2", step: "pll", frequency: 17 },
  { value: "R2 U' R' U' R U R U R U' R", step: "pll", frequency: 10 },
  { value: "M2 U M' U2 M U M2", step: "pll", frequency: 6 },
  { value: "R' U R' U' R3 U' R' U R U R2", step: "pll", frequency: 27 },
  { value: "M2 U' M U2 M' U' M2", step: "pll", frequency: 14 },
  { value: "R2 U R U R' U' R3 U' R' U R'", step: "pll", frequency: 12 },
  { value: "R2 U R U R' U' R' U' R' U R'", step: "pll", frequency: 11 },
  { value: "R' U R' U' R' U' R' U R U R2", step: "pll", frequency: 10 },
  { value: "R' U R' d' R' F' R2 U' R' U R' F R F", step: "pll", frequency: 17 },
  { value: "R' U R' U' R D' R' D R' D' U R2 U' R2 D R2", step: "pll", frequency: 15 },
  { value: "L' U L' y' U' R' F' R2 U' R' U R' F R F", step: "pll", frequency: 1 },
  { value: "R' U R' d' R' F' R2 U' R' U R' F R F d", step: "pll", frequency: 1 },
  { value: "R' U R' d' x R' F R' F' R2 U' R' U l F", step: "pll", frequency: 1 },
  { value: "F R U' R' U' R U R' F' R U R' U' R' F R F'", step: "pll", frequency: 36 },
  { value: "B' R B R' U' R' U R2 U R' U' R' F R F'", step: "pll", frequency: 1 },
  { value: "F' L' U L U L' U' L F L' U' L U L F' L' F", step: "pll", frequency: 1 },
  { value: "F R' F R2 U' R' U' R U R' F' R U R' U' F'", step: "pll", frequency: 1 },
  { value: "M' U' M2 U' M2 U' M' U2 M2", step: "pll", frequency: 7 },
  { value: "M2 U M2 U M' U2 M2 U2 M'", step: "pll", frequency: 6 },
  { value: "R' U' R U' R U R U' R' U R U R2 U' R'", step: "pll", frequency: 6 },
  { value: "M' U M2 U M2 U M' U2 M2", step: "pll", frequency: 3 },
  { value: "M' U2 M2 U2 M' U M2 U M2", step: "pll", frequency: 2 }
];

export const ollFrequencies = [
  { value: "R U2 R2 F R F' U2 R' F R F'", step: "oll", frequency: 3 },
  { value: "R U' R2 D' r U' r' D R2 U R'", step: "oll", frequency: 1 },
  { value: "R U' R2 D' r U r' D R2 U R'", step: "oll", frequency: 3 },
  { value: "F R U R' U' S R U R' U' f'", step: "oll", frequency: 2 },
  { value: "F R U R' U' F' U2 F U R U' R' F'", step: "oll", frequency: 1 },
  { value: "R U' r' R' r R' D' r U r' D R2 U R'", step: "oll", frequency: 1 },
  { value: "f R U R' U' f' U' F R U R' U' F'", step: "oll", frequency: 3 },
  { value: "L' l U l' U2 l U L' U L M'", step: "oll", frequency: 1 },
  { value: "R' F2 R2 U2 R' F R U2 R2 F2 R", step: "oll", frequency: 1 },
  { value: "f R U R' U' f' R' F' U' F U R", step: "oll", frequency: 1 },
  { value: "f R U R' U' f' U F R U R' U' F'", step: "oll", frequency: 2 },
  { value: "F U R U' R' F' U' F R U R' U' F'", step: "oll", frequency: 1 },
  { value: "f R U R' U' y x R' F R U R' U' F'", step: "oll", frequency: 1 },
  { value: "f R U R' d' x R' F R U R' U' F'", step: "oll", frequency: 1 },
  { value: "f R U R' d' x R' F R U R' U' f' S", step: "oll", frequency: 1 },
  { value: "l' U2 L U L' U l", step: "oll", frequency: 16 },
  { value: "r' U2 R U R' U r", step: "oll", frequency: 15 },
  { value: "F R R' F' l' U2 L U L' U l", step: "oll", frequency: 1 },
  { value: "R' F2 r U r' F R", step: "oll", frequency: 1 },
  { value: "r' U2 R U R2 R U r", step: "oll", frequency: 1 },
  { value: "r U2 R' U' R U' r'", step: "oll", frequency: 26 },
  { value: "U r U2 R' U' R U' r'", step: "oll", frequency: 1 },
  { value: "y U r U2 R' U' R U' r'", step: "oll", frequency: 1 },
  { value: "r U R' U R U2 r'", step: "oll", frequency: 27 },
  { value: "U' r U R' U R U2 r'", step: "oll", frequency: 1 },
  { value: "r U R' U R U' U' r'", step: "oll", frequency: 1 },
  { value: "r U R' U r U2 U2 r' R U2 r'", step: "oll", frequency: 1 },
  { value: "l' U' L U' L' U2 l", step: "oll", frequency: 19 },
  { value: "r' U' R U' R' U2 r", step: "oll", frequency: 9 },
  { value: "R' F' r U' r' F2 R", step: "oll", frequency: 5 },
  { value: "R R' U' r' U' R U' R' U2 r", step: "oll", frequency: 1 },
  { value: "R U2 R' U2 R' F R F'", step: "oll", frequency: 1 },
  { value: "R U R' U' R' F R2 U R' U' F'", step: "oll", frequency: 25 },
  { value: "F F' R U R' U' R' F R2 U R' U' F'", step: "oll", frequency: 1 },
  { value: "L' U' L U' L F' L' F L' U2 L", step: "oll", frequency: 1 },
  { value: "R' U' R y' x' R U' R' F R U l'", step: "oll", frequency: 1 },
  { value: "R U R' U R' F R F' R U2 R'", step: "oll", frequency: 17 },
  { value: "R U R' y R' F R U' R' F' R", step: "oll", frequency: 3 },
  { value: "F U F' R' F R U' R' F' R", step: "oll", frequency: 2 },
  { value: "L U L' y' R' F R U' R' F' R", step: "oll", frequency: 2 },
  { value: "L U L' x' z L' U L F' L' U' r", step: "oll", frequency: 1 },
  { value: "r' R2 U R' U R U2 R' U M'", step: "oll", frequency: 16 },
  { value: "r U R' U R' F R F' R U2 r'", step: "oll", frequency: 3 },
  { value: "F F' U2 r' R2 U R' U R U2 R' U M'", step: "oll", frequency: 1 },
  { value: "l' L2 U L' U L U2 L' U L' l", step: "oll", frequency: 1 },
  { value: "r' R2 R' R U R' U R U2 R' U M'", step: "oll", frequency: 1 },
  { value: "r R2 U' R U' R' U2 R U' r' R", step: "oll", frequency: 14 },
  { value: "R' M' U' R U' R' U2 R U' r' R", step: "oll", frequency: 7 },
  { value: "l L2 U' L U' L' U2 L U' L l'", step: "oll", frequency: 2 },
  { value: "F U R U2 R' U' R U R' F'", step: "oll", frequency: 10 },
  { value: "F U R U' R2 F' R U R U' R'", step: "oll", frequency: 7 },
  { value: "r U' r' U' r U r' F' U F", step: "oll", frequency: 4 },
  { value: "r U' r' U' r U r' y' R' U R", step: "oll", frequency: 2 },
  { value: "x' R U' R' F' R U R' U' F U x", step: "oll", frequency: 1 },
  { value: "R' F R U R' F' R F U' F'", step: "oll", frequency: 24 },
  { value: "R' F R U R' F' R y' R U' R'", step: "oll", frequency: 2 },
  { value: "F F' R R2 F R U R' F' R y' R U' R'", step: "oll", frequency: 1 },
  { value: "R' F R l' l U l' U' l y' R U' R'", step: "oll", frequency: 1 },
  { value: "l' U l U l' U' l y' R U' R'", step: "oll", frequency: 1 },
  { value: "r' U' r R' U' R U r' U r", step: "oll", frequency: 12 },
  { value: "l' U' l L' U' L U l' U l", step: "oll", frequency: 8 },
  { value: "r' U' M' U' R U r' U r", step: "oll", frequency: 7 },
  { value: "l' l U l' U' l L' U' L U l' U l", step: "oll", frequency: 1 },
  { value: "r U r' R U R' U' r U' r'", step: "oll", frequency: 24 },
  { value: "R' F R U R' U' F' R U' R' U2 R", step: "oll", frequency: 1 },
  { value: "R R' r U r' R U R' U' r U' r'", step: "oll", frequency: 1 },
  { value: "r U U' U r' R U R' U' r U' r'", step: "oll", frequency: 1 },
  { value: "R U R' U R' F R F' U2 R' F R F'", step: "oll", frequency: 5 },
  { value: "F R' F' R2 r' U R U' R' U' M'", step: "oll", frequency: 1 },
  { value: "F R' F' R U2 R U' B U' B' R'", step: "oll", frequency: 1 },
  { value: "F R' F' R U S' R U' R' S", step: "oll", frequency: 1 },
  { value: "r U' r' F U2 F U' R U' R' F'", step: "oll", frequency: 1 },
  { value: "R U2 R2 F R F' U2 M' U R U' r'", step: "oll", frequency: 4 },
  { value: "R U R2 F' U' F U R U2 R' F R F'", step: "oll", frequency: 1 },
  { value: "R y R U R' d R' U2 R' F R F'", step: "oll", frequency: 1 },
  { value: "r U R' U R U2 r2 U' R U' R' U2 r", step: "oll", frequency: 1 },
  { value: "M U R U R' U' r R2 F R F'", step: "oll", frequency: 2 },
  { value: "S' R U R' S U' R' F R F'", step: "oll", frequency: 2 },
  { value: "r' R U R U R' U' r R2 F R F'", step: "oll", frequency: 2 },
  { value: "L' l U R U R' U' M' R' F R F'", step: "oll", frequency: 1 },
  { value: "l L' U R U R' U' r R2 F R F'", step: "oll", frequency: 1 },
  { value: "r' R U R U R' U' r M' R' U R U' r'", step: "oll", frequency: 1 },
  { value: "r U R' U' M2 U R U' R' U' M'", step: "oll", frequency: 1 },
  { value: "R U2 R' U' R U R' U' R U' R'", step: "oll", frequency: 8 },
  { value: "R U R' U R U' R' U R U2 R'", step: "oll", frequency: 6 },
  { value: "R U R' U R U L' U R' U' L", step: "oll", frequency: 5 },
  { value: "F R U' R' U R U2 R' U' R U R' U' F'", step: "oll", frequency: 2 },
  { value: "F R U R' U' R U R' U' R U R' U' F'", step: "oll", frequency: 2 },
  { value: "R U2 R2 U' R2 U' R2 U2 R", step: "oll", frequency: 18 },
  { value: "F U R U' R' U R U2 R' U' R U R' F'", step: "oll", frequency: 3 },
  { value: "R U R' U' R' F R2 U R' U' R U R' U' F'", step: "oll", frequency: 3 },
  { value: "F U R U' R' U R U' R2 F' R U R U' R'", step: "oll", frequency: 2 },
  { value: "F U R U2 R' U R U R' F' R U2 R' U' R U' R'", step: "oll", frequency: 2 },
  { value: "R2 D' R U2 R' D R U2 R", step: "oll", frequency: 15 },
  { value: "R2 D R' U2 R D' R' U2 R'", step: "oll", frequency: 8 },
  { value: "F R U' R' U R U R' U R U' R' F'", step: "oll", frequency: 4 },
  { value: "R' U2 R U R' U R' D' R U' R' D R U R", step: "oll", frequency: 3 },
  { value: "R' U R U R' U2 R D' U' R U' R' U2 R U' R' D", step: "oll", frequency: 3 },
  { value: "r U R' U' r' F R F'", step: "oll", frequency: 14 },
  { value: "l' U' L U l F' L' F", step: "oll", frequency: 10 },
  { value: "l' U' L U R U' r' F", step: "oll", frequency: 5 },
  { value: "R' U' R' D' R U R' D R U2 R U R' U R", step: "oll", frequency: 3 },
  { value: "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'", step: "oll", frequency: 3 },
  { value: "F R' F' r U R U' r'", step: "oll", frequency: 11 },
  { value: "F' r U R' U' r' F R", step: "oll", frequency: 9 },
  { value: "R U2 R D R' U2 R D' R2", step: "oll", frequency: 8 },
  { value: "R' U2 R' D' r U2 r' D R2", step: "oll", frequency: 6 },
  { value: "R2 D' R U' R' D R U R", step: "oll", frequency: 4 },
  { value: "R' U' R U' R' U2 R", step: "oll", frequency: 27 },
  { value: "R U2 R' U' R U' R'", step: "oll", frequency: 20 },
  { value: "L' U' L U' L' U2 L", step: "oll", frequency: 8 },
  { value: "R' U' R U' R' U' U' R", step: "oll", frequency: 1 },
  { value: "U R D R' U' R D' R2 U' R U2 R' U' R", step: "oll", frequency: 1 },
  { value: "R U R' U R U2 R'", step: "oll", frequency: 34 },
  { value: "R' U2 R U R' U R", step: "oll", frequency: 11 },
  { value: "R U' L' U R' U' L", step: "oll", frequency: 2 },
  { value: "R U R' U R U' U' R'", step: "oll", frequency: 2 },
  { value: "F R' U2 R F' R' F U2 F' R", step: "oll", frequency: 1 },
  { value: "r U R' U' r' R U R U' R'", step: "oll", frequency: 24 },
  { value: "r U R' U' M U R U' R'", step: "oll", frequency: 3 },
  { value: "M' U M U2 M' U M", step: "oll", frequency: 1 },
  { value: "r' U' R U M' U' R' U R", step: "oll", frequency: 1 },
  { value: "R U R' U' R U' R' F' U' F R U R'", step: "oll", frequency: 14 },
  { value: "r2 D' r U r' D r2 U' r' U' r", step: "oll", frequency: 8 },
  { value: "U R U R' U' R U' R' F' U' F R U R'", step: "oll", frequency: 2 },
  { value: "L F R' F R F2 L2 U' L U' L' U2 L", step: "oll", frequency: 1 },
  { value: "R' U' R U' R' U2 F R U R' U' F' U R", step: "oll", frequency: 1 },
  { value: "F U R U2 R' U' R U2 R' U' F'", step: "oll", frequency: 8 },
  { value: "r' D' r U' r' D r2 U' r' U r U r'", step: "oll", frequency: 5 },
  { value: "F R' F R2 U' R' U' R U R' F2", step: "oll", frequency: 4 },
  { value: "F U2 U' R U2 R' U' R U2 R' U' F'", step: "oll", frequency: 1 },
  { value: "F U R U2 R' U' R U R' R U R' U' F'", step: "oll", frequency: 1 },
  { value: "R' U' F U R U' R' F' R", step: "oll", frequency: 20 },
  { value: "U R' U' F U R U' R' F' R", step: "oll", frequency: 2 },
  { value: "R' R U' F R' F' R U R U R' U' R U' R'", step: "oll", frequency: 1 },
  { value: "R R' U' R' U' F U R U' R' F' R", step: "oll", frequency: 1 },
  { value: "S' L' U' L U L F' L' f", step: "oll", frequency: 1 },
  { value: "S R U R' U' R' F R f'", step: "oll", frequency: 12 },
  { value: "L U F' U' L' U L F L'", step: "oll", frequency: 6 },
  { value: "R U B' U' R' U R B R'", step: "oll", frequency: 5 },
  { value: "F U R U' F' r U R' U' r'", step: "oll", frequency: 2 },
  { value: "f F' R U R' U' R' F R f'", step: "oll", frequency: 1 },
  { value: "R U R' U' R' F R F'", step: "oll", frequency: 28 },
  { value: "F R U' R' U R U R' F'", step: "oll", frequency: 2 },
  { value: "L' U' L U L F' L' F", step: "oll", frequency: 2 },
  { value: "R U R2 U' R' F R U R U' F'", step: "oll", frequency: 5 },
  { value: "R U R' d' l' U' L U L' l", step: "oll", frequency: 2 },
  { value: "R U R' d' l' U' L U r' R", step: "oll", frequency: 2 },
  { value: "f R f' U' r' U' R U M'", step: "oll", frequency: 2 },
  { value: "F' U' F U r U R' U' r' R", step: "oll", frequency: 1 },
  { value: "R U2 R2 F R F' R U2 R'", step: "oll", frequency: 19 },
  { value: "L' U2 L2 F' L' F L' U2 L", step: "oll", frequency: 1 },
  { value: "R' U2 R l U' R' U l' U2 R", step: "oll", frequency: 1 },
  { value: "R U' R2 R2 U' R2 F R F' R U2 R'", step: "oll", frequency: 1 },
  { value: "R U2 R' y U' R' F R U' R' F' R", step: "oll", frequency: 1 },
  { value: "L' U' L U' L' U L U L F' L' F", step: "oll", frequency: 17 },
  { value: "R U R' F' R U R' U' R' F R U' R' F R F'", step: "oll", frequency: 4 },
  { value: "L' U' L U' L' U L U L F' L' f f' F", step: "oll", frequency: 1 },
  { value: "L' U' L U' L' U L U r U' r' F", step: "oll", frequency: 1 },
  { value: "R' F' U' F2 U R U' R' F' R", step: "oll", frequency: 1 },
  { value: "F R U' R' U' R U R' F'", step: "oll", frequency: 26 },
  { value: "F R' F' R U R U' R'", step: "oll", frequency: 16 },
  { value: "F' L F L' U' L' U L", step: "oll", frequency: 2 },
  { value: "F R U2 U R' U' R U R' F'", step: "oll", frequency: 2 },
  { value: "F R' R2 U' R' U' R U R' F'", step: "oll", frequency: 1 },
  { value: "R U R' U R U' R' U' R' F R F'", step: "oll", frequency: 23 },
  { value: "R U R' U R U' R2 R U' R' F R F'", step: "oll", frequency: 1 },
  { value: "U' R U R' U R U' R' U' R' F R F'", step: "oll", frequency: 1 },
  { value: "r r' R U R' U R U' R' U' R' F R F'", step: "oll", frequency: 1 },
  { value: "L F' L' U' L U F U' L'", step: "oll", frequency: 10 },
  { value: "R U R' F' U' F U R U2 R'", step: "oll", frequency: 7 },
  { value: "f' r U r' U' r' F r S", step: "oll", frequency: 3 },
  { value: "L F' L' U' L U F2 F' U' L'", step: "oll", frequency: 1 },
  { value: "L F' L' U' L d R U' F'", step: "oll", frequency: 1 },
  { value: "R' F R U R' U' F' U R", step: "oll", frequency: 26 },
  { value: "F R U R' U' F' R U R' U R U2 R'", step: "oll", frequency: 1 },
  { value: "R' F F' R U2 R' F R U R' U' F' U R", step: "oll", frequency: 1 },
  { value: "R U R' F' U' F R U R' U' R U' R'", step: "oll", frequency: 1 },
  { value: "R U R' U R U2 R' F R U R' U' F'", step: "oll", frequency: 22 },
  { value: "F F' R U R' U R U2 R' F R U R' U' F'", step: "oll", frequency: 1 },
  { value: "F U R2 D R' U' R D' R2 F'", step: "oll", frequency: 1 },
  { value: "F U R U' R' F' U R U' r' F R' F' r", step: "oll", frequency: 1 },
  { value: "F U R U' R' F' U R U R' U R U2 R'", step: "oll", frequency: 1 },
  { value: "R' U' R U' R' U2 R F R U R' U' F'", step: "oll", frequency: 20 },
  { value: "R' U' R U' R' U2 R U R' F' U' F U R", step: "oll", frequency: 5 },
  { value: "R' F R F' R' F R F' R U R' U' R U R'", step: "oll", frequency: 4 },
  { value: "F R' F' R U2 R' U' R2 U' R2 U2 R", step: "oll", frequency: 3 },
  { value: "F S' R U R' U' F' U S", step: "oll", frequency: 2 },
  { value: "R' U' F' U F R", step: "oll", frequency: 33 },
  { value: "F' U' L' U L F", step: "oll", frequency: 2 },
  { value: "R' R U' R' U' F' U F R", step: "oll", frequency: 1 },
  { value: "R' U' F R' F' R U R", step: "oll", frequency: 1 },
  { value: "U R' U' F' U F R", step: "oll", frequency: 1 },
  { value: "F U R U' R' F'", step: "oll", frequency: 33 },
  { value: "f R U R' U' f'", step: "oll", frequency: 10 },
  { value: "S F R U R' U' f'", step: "oll", frequency: 2 },
  { value: "S R R' F R U R' U' f'", step: "oll", frequency: 1 },
  { value: "y' U' F U R U' R' F'", step: "oll", frequency: 1 },
  { value: "F R U R' U' F'", step: "oll", frequency: 23 },
  { value: "R' F' U' F U R", step: "oll", frequency: 5 },
  { value: "R' R F R U R' U' F'", step: "oll", frequency: 1 },
  { value: "R' U' R' F R F' U R", step: "oll", frequency: 26 },
  { value: "R' F F' R U R' U' R' F R F' U R", step: "oll", frequency: 1 },
  { value: "R2 R U' R' F R F' U R", step: "oll", frequency: 1 },
  { value: "U' R' U' R' F R F' U R", step: "oll", frequency: 1 },
  { value: "U R' U' R' F R F' U R", step: "oll", frequency: 1 },
  { value: "F R' F' R U2 R U' R' U R U2 R'", step: "oll", frequency: 11 },
  { value: "R' U' R' F R F' R' F R F' U R", step: "oll", frequency: 9 },
  { value: "F' L' U' L U L' U' L U F", step: "oll", frequency: 8 },
  { value: "R' F' U' F U F' U' F U R", step: "oll", frequency: 4 },
  { value: "F U R U' R' F' R U' L' U R' U' L", step: "oll", frequency: 2 },
  { value: "F R U R' U' R U R' U' F'", step: "oll", frequency: 27 },
  { value: "R' U' F' U F R2 U2 R' U' R U' R'", step: "oll", frequency: 2 },
  { value: "F R U R' U' R2 D R' U R D' R2 U' F'", step: "oll", frequency: 1 },
  { value: "R U2 R' U' R U R' U2 R' F R F'", step: "oll", frequency: 1 },
  { value: "U' F R U R' U' R U R' U' F'", step: "oll", frequency: 1 },
  { value: "r U' r2 U r2 U r2 U' r", step: "oll", frequency: 19 },
  { value: "l U' l2 U l2 U l2 U' l", step: "oll", frequency: 3 },
  { value: "r r' U r U' r2 U r2 U r2 U' r", step: "oll", frequency: 2 },
  { value: "R' U2 R U R' U R F R U R' U' F'", step: "oll", frequency: 1 },
  { value: "r r' U' R U2 R' U' R U' R' U' R' U' F' U F R", step: "oll", frequency: 1 },
  { value: "l' U l2 U' l2 U' l2 U l'", step: "oll", frequency: 13 },
  { value: "r' U r2 U' r2 U' r2 U r'", step: "oll", frequency: 8 },
  { value: "R' F R2 B' R2 F' R2 B R'", step: "oll", frequency: 3 },
  { value: "l' U l2 U' l2 l2 l2 U' l2 U l'", step: "oll", frequency: 2 },
  { value: "l' U l2 U' l2 l2 U U' l2 l2 l2 U' l2 U l'", step: "oll", frequency: 1 },
  { value: "F U R U' R' U R U' R' F'", step: "oll", frequency: 17 },
  { value: "f R U R' U' R U R' U' f'", step: "oll", frequency: 7 },
  { value: "F' U' L' U L U' L' U L F", step: "oll", frequency: 1 },
  { value: "R' F F' R U' R' U' F' U F U' F' U F R", step: "oll", frequency: 1 },
  { value: "R U R' U R U' B U' B' R'", step: "oll", frequency: 8 },
  { value: "R' F' U' F U' R U R' U R", step: "oll", frequency: 6 },
  { value: "F R U R' y' U R' U' R U' R'", step: "oll", frequency: 3 },
  { value: "R U R' U R d' R U' R' F'", step: "oll", frequency: 2 },
  { value: "F R U R' U' F' U' R U2 R' U' R U' R'", step: "oll", frequency: 1 },
  { value: "l' U' L U' L' U L U' L' U2 l", step: "oll", frequency: 8 },
  { value: "r' U2 R U R' U' R U R' U r", step: "oll", frequency: 7 },
  { value: "r' U' R U' R' U R U' R' U2 r", step: "oll", frequency: 6 },
  { value: "R' F' r U' r' F r U' r' F2 R", step: "oll", frequency: 2 },
  { value: "F R' F' R U R U' R' U R' U' R U' R' U2 R", step: "oll", frequency: 1 },
  { value: "r U2 R' U' R U R' U' R U' r'", step: "oll", frequency: 11 },
  { value: "r U R' U R U' R' U R U2 r'", step: "oll", frequency: 9 },
  { value: "R' U' F' U F R U2 U' r U R' U' r' F R F'", step: "oll", frequency: 1 },
  { value: "r U' U2 R' U R U' R' U R U2 r'", step: "oll", frequency: 1 },
  { value: "r U R' U R U2 R' U U' R U R' U R U2 r'", step: "oll", frequency: 1 },
  { value: "R' F R U R U' R2 F' R2 U' R' U R U R'", step: "oll", frequency: 8 },
  { value: "F U' R2 D R' U2 R D' R2 U F'", step: "oll", frequency: 1 },
  { value: "R' F U R U' R2 F' R2 U R' U' R", step: "oll", frequency: 1 },
  { value: "U' R' F R U R U' R2 F' R2 U' R' U R U R'", step: "oll", frequency: 1 },
  { value: "r U2 R' U' r' R2 U R' U' r U' r'", step: "oll", frequency: 1 },
  { value: "r U r' U R U' R' U R U' R' r U' r'", step: "oll", frequency: 3 },
  { value: "F R U R' U' F' r U R' U' r' F R F'", step: "oll", frequency: 2 },
  { value: "F R U R' U' F' U2 l' U' L U l F' L' F", step: "oll", frequency: 1 },
  { value: "R U R' U' M' U R U' r'", step: "oll", frequency: 10 },
  { value: "R U R' U' r R' U R U' r'", step: "oll", frequency: 4 },
  { value: "R' U' R U M U' R' U r", step: "oll", frequency: 1 },
  { value: "R U R' M' r' R U' M' U R U' r'", step: "oll", frequency: 1 }
];