  
import type { Case } from './LLpatternBuilder';

/**
 * Development only file for building the patterns.json files.
 */
export const ollCases: Case[] = [
  { alg: "R U2 R2 F R F' U2 R' F R F'", index: 1, name: '1', step: "oll"},
  { alg: "R U' R2 D' r U r' D R2 U R'", index: 2, name: '2', step: "oll"},
  { alg: "f R U R' U' f' U' F R U R' U' F'", index: 3, name: '3', step: "oll"},
  { alg: "f R U R' U' f' U F R U R' U' F'", index: 4, name: '4', step: "oll"},
  { alg: "l' U2 L U L' U l", index: 5, name: '5', step: "oll"},
  { alg: "r U2 R' U' R U' r'", index: 6, name: '6', step: "oll"},
  { alg: "r U R' U R U2 r'", index: 7, name: '7', step: "oll"},
  { alg: "l' U' L U' L' U2 l", index: 8, name: '8', step: "oll"},
  { alg: "R U R' U' R' F R2 U R' U' F'", index: 9, name: '9', step: "oll"},
  { alg: "R U R' U R' F R F' R U2 R'", index: 10, name: '10', step: "oll"},
  { alg: "r' R2 U R' U R U2 R' U M'", index: 11, name: '11', step: "oll"},
  { alg: "r R2 U' R U' R' U2 R U' r' R", index: 12, name: '12', step: "oll"},
  { alg: "F U R U2 R' U' R U R' F'", index: 13, name: '13', step: "oll"},
  { alg: "R' F R U R' F' R F U' F'", index: 14, name: '14', step: "oll"},
  { alg: "r' U' r R' U' R U r' U r", index: 15, name: '15', step: "oll"},
  { alg: "r U r' R U R' U' r U' r'", index: 16, name: '16', step: "oll"},
  { alg: "R U R' U R' F R F' U2 R' F R F'", index: 17, name: '17', step: "oll"},
  { alg: "R U2 R2 F R F' U2 M' U R U' r'", index: 18, name: '18', step: "oll"},
  { alg: "S' R U R' S U' R' F R F'", index: 19, name: '19', step: "oll"},
  { alg: "r U R' U' M2 U R U' R' U' M'", index: 20, name: '20', step: "oll"},
  { alg: "R U2 R' U' R U R' U' R U' R'", index: 21, name: '21', step: "oll"},
  { alg: "R U2 R2 U' R2 U' R2 U2 R", index: 22, name: '22', step: "oll"},
  { alg: "R2 D' R U2 R' D R U2 R", index: 23, name: '23', step: "oll"},
  { alg: "r U R' U' r' F R F'", index: 24, name: '24', step: "oll"},
  { alg: "F R' F' r U R U' r'", index: 25, name: '25', step: "oll"},
  { alg: "R' U' R U' R' U2 R", index: 26, name: '26', step: "oll"},
  { alg: "R U R' U R U2 R'", index: 27, name: '27', step: "oll"},
  { alg: "r U R' U' r' R U R U' R'", index: 28, name: '28', step: "oll"},
  { alg: "R U R' U' R U' R' F' U' F R U R'", index: 29, name: '29', step: "oll"},
  { alg: "F U R U2 R' U' R U2 R' U' F'", index: 30, name: '30', step: "oll"},
  { alg: "R' U' F U R U' R' F' R", index: 31, name: '31', step: "oll"},
  { alg: "S R U R' U' R' F R f'", index: 32, name: '32', step: "oll"},
  { alg: "R U R' U' R' F R F'", index: 33, name: '33', step: "oll"},
  { alg: "R U R2 U' R' F R U R U' F'", index: 34, name: '34', step: "oll"},
  { alg: "R U2 R2 F R F' R U2 R'", index: 35, name: '35', step: "oll"},
  { alg: "L' U' L U' L' U L U L F' L' F", index: 36, name: '36', step: "oll"},
  { alg: "F R U' R' U' R U R' F'", index: 37, name: '37', step: "oll"},
  { alg: "R U R' U R U' R' U' R' F R F'", index: 38, name: '38', step: "oll"},
  { alg: "L F' L' U' L U F U' L'", index: 39, name: '39', step: "oll"},
  { alg: "R' F R U R' U' F' U R", index: 40, name: '40', step: "oll"},
  { alg: "R U R' U R U2 R' F R U R' U' F'", index: 41, name: '41', step: "oll"},
  { alg: "R' U' R U' R' U2 R F R U R' U' F'", index: 42, name: '42', step: "oll"},
  { alg: "R' U' F' U F R", index: 43, name: '43', step: "oll"},
  { alg: "F U R U' R' F'", index: 44, name: '44', step: "oll"},
  { alg: "F R U R' U' F'", index: 45, name: '45', step: "oll"},
  { alg: "R' U' R' F R F' U R", index: 46, name: '46', step: "oll"},
  { alg: "F R' F' R U2 R U' R' U R U2 R'", index: 47, name: '47', step: "oll"},
  { alg: "F R U R' U' R U R' U' F'", index: 48, name: '48', step: "oll"},
  { alg: "r U' r2 U r2 U r2 U' r", index: 49, name: '49', step: "oll"},
  { alg: "l' U l2 U' l2 U' l2 U l'", index: 50, name: '50', step: "oll"},
  { alg: "F U R U' R' U R U' R' F'", index: 51, name: '51', step: "oll"},
  { alg: "R U R' U R U' B U' B' R'", index: 52, name: '52', step: "oll"},
  { alg: "l' U' L U' L' U L U' L' U2 l", index: 53, name: '53', step: "oll"},
  { alg: "r U2 R' U' R U R' U' R U' r'", index: 54, name: '54', step: "oll"},
  { alg: "R' F R U R U' R2 F' R2 U' R' U R U R'", index: 55, name: '55', step: "oll"},
  { alg: "r U r' U R U' R' U R U' R' r U' r'", index: 56, name: '56', step: "oll"},
  { alg: "R U R' U' M' U R U' r'", index: 57, name: '57', step: "oll"},
 ];

export const pllCases: Case[] = [
  { alg: "x R' U R' D2 R U' R' D2 R2", index: 1, name: 'Aa', step: "pll"},
  { alg: "x R2 D2 R U R' D2 R U' R", index: 2, name: 'Ab', step: "pll"},
  { alg: "x' R U' R' D R U R' D' R U R' D R U' R' D'", index: 3, name: 'E', step: "pll"},
  { alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", index: 4, name: 'F', step: "pll"},
  { alg: "R2 U R' U R' U' R U' R2 D U' R' U R D'", index: 5, name: 'Ga', step: "pll"},
  { alg: "R' U' R D' U R2 U R' U R U' R U' R2 D", index: 6, name: 'Gb', step: "pll"},
  { alg: "R2 F2 R U2 R U2 R' F R U R' U' R' F R2", index: 7, name: 'Gc', step: "pll"},
  { alg: "R U R' D U' R2 U' R U' R' U R' U R2 D'", index: 8, name: 'Gd', step: "pll"},
  { alg: "M2 U M2 U2 M2 U M2", index: 9, name: 'H', step: "pll"},
  { alg: "R' U L' U2 R U' R' U2 R L", index: 10, name: 'Ja', step: "pll"},
  { alg: "R U R' F' R U R' U' R' F R2 U' R'", index: 11, name: 'Jb', step: "pll"},
  { alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'", index: 12, name: 'Na', step: "pll"},
  { alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R", index: 13, name: 'Nb', step: "pll"},
  { alg: "R U' R' U' R U R D R' U' R D' R' U2 R'", index: 14, name: 'Ra', step: "pll"},
  { alg: "R' U2 R' D' R U' R' D R U R U' R' U' R", index: 15, name: 'Rb', step: "pll"},
  { alg: "R U R' U' R' F R2 U' R' U' R U R' F'", index: 16, name: 'T', step: "pll"},
  { alg: "R U R' U R' U' R2 U' R' U R' U R", index: 17, name: 'Ua', step: "pll"},
  { alg: "R' U R' U' R3 U' R' U R U R2", index: 18, name: 'Ub', step: "pll"},
  { alg: "R' U R' d' R' F' R2 U' R' U R' F R F", index: 19, name: 'V', step: "pll"},
  { alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'", index: 20, name: 'Y', step: "pll"},
  { alg: "M' U' M2 U' M2 U' M' U2 M2", index: 21, name: 'Z', step: "pll"}
];

export const zbllCases: Case[] = [
  { alg: "R U R' U R U2 R' U2 R' U' R U' R' U2 R", index: 1, name: 'T 72', step: "zbll"},
  { alg: "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'", index: 2, name: 'T 71', step: "zbll"},
  { alg: "R' U2 R U R' U R2 U2 R' U' R U' R'", index: 3, name: 'T 70', step: "zbll"},
  { alg: "R U2 R' U' R U' R2 U2 R U R' U R", index: 4, name: 'T 69', step: "zbll"},
  { alg: "R' U2 R U R' U R U' R' U' R U' R' U2 R", index: 5, name: 'T 66', step: "zbll"},
  { alg: "R U R' U R U2 R' U' R U2 R' U' R U' R'", index: 6, name: 'T 62', step: "zbll"},
  { alg: "R U R' U R U' R' U R' U' R2 U' R2 U2 R", index: 7, name: 'T 63', step: "zbll"},
  { alg: "R U R2 U' R2 U' R2 U2 R U' R U' R'", index: 8, name: 'T 68', step: "zbll"},
  { alg: "R' U' R U' R' U R U' R U R2 U R2 U2 R'", index: 9, name: 'T 65', step: "zbll"},
  { alg: "R' U' R2 U R2 U R2 U2 R' U R' U R", index: 10, name: 'T 67', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U R U R' U R U2 R'", index: 11, name: 'T 64', step: "zbll"},
  { alg: "R U' R' U2 R U R' U2 R U R' U R U' R'", index: 12, name: 'T 61', step: "zbll"},
  { alg: "R2 F R U R' U' R' F' R' U' R2 U2 R U2 R", index: 13, name: 'T 54', step: "zbll"},
  { alg: "F U R' D' R U R' D R U' R' D' R U' R' D R F'", index: 14, name: 'T 53', step: "zbll"},
  { alg: "R U' R2 D' r U2 r' D R2 U R'", index: 15, name: 'T 55', step: "zbll"},
  { alg: "R' U R2 D r' U2 r D' R2 U' R", index: 16, name: 'T 56', step: "zbll"},
  { alg: "R' U' R U2 R D R' U' R D' R2 U R U' R' U R", index: 17, name: 'T 57', step: "zbll"},
  { alg: "R U R' F' R U R' U' R' F R U' R' F R U R U' R' F'", index: 18, name: 'T 60', step: "zbll"},
  { alg: "R U R' U' R U R2 D' R U' R' D R U2 R U' R'", index: 19, name: 'T 59', step: "zbll"},
  { alg: "R' D' R U' R' D R U' R U' R' U R U' R' U' R U R'", index: 20, name: 'T 58', step: "zbll"},
  { alg: "R U R' U2 R' D' R U R' D R2 U' R' U R U' R'", index: 21, name: 'T 52', step: "zbll"},
  { alg: "R U' R2 D' r U2 r' D R2 U' R' U' R U' R'", index: 22, name: 'T 51', step: "zbll"},
  { alg: "R' U' R U R' U' R2 D R' U R D' R' U2 R' U R", index: 23, name: 'T 49', step: "zbll"},
  { alg: "R U' R' U R U R' U' R U R' U R' D' R U R' D R", index: 24, name: 'T 50', step: "zbll"},
  { alg: "R' U' R U' R2 F' R U R U' R' F U R U' R' U2 R", index: 25, name: 'T 18', step: "zbll"},
  { alg: "r U R' U' r' F R F'", index: 26, name: 'T 17', step: "zbll"},
  { alg: "L U2 L' F' U L U' L' U' F L U' L'", index: 27, name: 'T 19', step: "zbll"},
  { alg: "R U R' U' R U' R' L U' R U R' L'", index: 28, name: 'T 20', step: "zbll"},
  { alg: "R U2 R' U2 R' F R U R U' R' F'", index: 29, name: 'T 21', step: "zbll"},
  { alg: "R L' U R' U' L U R U R' U' R U' R'", index: 30, name: 'T 24', step: "zbll"},
  { alg: "F U' B' R2 U' R2 U R2 F' B", index: 31, name: 'T 23', step: "zbll"},
  { alg: "F' U' r' F2 r U F R U' R'", index: 32, name: 'T 22', step: "zbll"},
  { alg: "F R U R' U' R' F' U2 R U R U' R2 U2 R", index: 33, name: 'T 16', step: "zbll"},
  { alg: "R U R' U R U R' U2 L R U' R' U L'", index: 34, name: 'T 15', step: "zbll"},
  { alg: "R' U' R U D' R U' R U R U' R2 D", index: 35, name: 'T 13', step: "zbll"},
  { alg: "R' D' R U R' D R2 U' R' U R U R' U' R U R'", index: 36, name: 'T 14', step: "zbll"},
  { alg: "R' U' R' D' R U R' D R2", index: 37, name: 'T 6', step: "zbll"},
  { alg: "F R U R' U' R U R' U' F' R U R' U' R' F R F'", index: 38, name: 'T 5', step: "zbll"},
  { alg: "R' U2 R F U' R' U R U F' R' U R", index: 39, name: 'T 7', step: "zbll"},
  { alg: "R U R' U' R U' R' U' F R U R' U' R' F' R", index: 40, name: 'T 8', step: "zbll"},
  { alg: "F U R U2 R' U R U R' F'", index: 41, name: 'T 9', step: "zbll"},
  { alg: "R' U R U R' U' R' D' R U2 R' D R U R", index: 42, name: 'T 12', step: "zbll"},
  { alg: "F U R' U' R F' R' U' R U R' U R", index: 43, name: 'T 11', step: "zbll"},
  { alg: "R U R' U' R' F' R U2 R U2 R' F", index: 44, name: 'T 10', step: "zbll"},
  { alg: "F R2 D R' U' R D' R2 U' R U2 R' U' F'", index: 45, name: 'T 4', step: "zbll"},
  { alg: "R2 F2 R U2 R U2 R' F2 R U' R' U R", index: 46, name: 'T 3', step: "zbll"},
  { alg: "R' U' R U' R' U' R U2 L' R' U R U' L", index: 47, name: 'T 1', step: "zbll"},
  { alg: "R' U2 R2 U R' U' R' U2 F' R U2 R U2 R' F", index: 48, name: 'T 2', step: "zbll"},
  { alg: "l U2 R D2 R' U2 R D2 R2 x", index: 49, name: 'T 42', step: "zbll"},
  { alg: "l' U2 R' D2 R U2 R' D2 R2 x'", index: 50, name: 'T 41', step: "zbll"},
  { alg: "F R U R' U' R U' R' U' R U R' F'", index: 51, name: 'T 43', step: "zbll"},
  { alg: "R U R' U2 R U' R' U2 R U' R2 F' R U R U' R' F", index: 52, name: 'T 44', step: "zbll"},
  { alg: "R' U' R' D' R U R' D R U' R U' R' U2 R", index: 53, name: 'T 45', step: "zbll"},
  { alg: "R U2 R' U' R U' R2 F' r U R U' r' F", index: 54, name: 'T 48', step: "zbll"},
  { alg: "r U R' U' r' F R F' R' U2 R U R' U R", index: 55, name: 'T 47', step: "zbll"},
  { alg: "R U R' U R' D' R U' R' D R U R U2 R'", index: 56, name: 'T 46', step: "zbll"},
  { alg: "R' U2 R' D' R U2 R' D R2 U' R' U2 R U R' U R", index: 57, name: 'T 40', step: "zbll"},
  { alg: "R' U' R U' F U' R' U R U F' R' U R", index: 58, name: 'T 39', step: "zbll"},
  { alg: "R' D' R U R' D R2 U R' U2 R U' R' U' R U' R'", index: 59, name: 'T 37', step: "zbll"},
  { alg: "R' U2 R' D' R U2 R' D R' U R' U R U2 R'", index: 60, name: 'T 38', step: "zbll"},
  { alg: "R' U2 R U R' U R F U R U2 R' U R U R' F'", index: 61, name: 'T 30', step: "zbll"},
  { alg: "F R U' R' U' R U2 R' U' F' R' U' R U' R' U2 R", index: 62, name: 'T 29', step: "zbll"},
  { alg: "r U' r U2 R' F R U2 r2 F", index: 63, name: 'T 31', step: "zbll"},
  { alg: "R' U' R2 U R' F' R U R' U' R' F R2 U' R' U' R' U R", index: 64, name: 'T 32', step: "zbll"},
  { alg: "R U' R' U R U R' U' R U R' U' R' D' R U' R' D R", index: 65, name: 'T 33', step: "zbll"},
  { alg: "L' U2 R U2 R' U2 L U R U R' U' R U' R'", index: 66, name: 'T 36', step: "zbll"},
  { alg: "F U' R' U2 R U F' R' U' R U R' U R", index: 67, name: 'T 35', step: "zbll"},
  { alg: "R U R' U R U' R' F' U' L' U2 L U F", index: 68, name: 'T 34', step: "zbll"},
  { alg: "f R f' R' U' R U R2 F R F' R", index: 69, name: 'T 28', step: "zbll"},
  { alg: "R U' R' U2 L R U' R' U L'", index: 70, name: 'T 27', step: "zbll"},
  { alg: "R' U R U2 L' R' U R U' L", index: 71, name: 'T 25', step: "zbll"},
  { alg: "R U R2 F R F' R U' R' F' U F", index: 72, name: 'T 26', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U2 R' U2 R U R' U R", index: 73, name: 'U 72', step: "zbll"},
  { alg: "R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2", index: 74, name: 'U 71', step: "zbll"},
  { alg: "R' U' R U' R' U2 R2 U R' U R U2 R'", index: 75, name: 'U 69', step: "zbll"},
  { alg: "R U R' U R U2 R2 U' R U' R' U2 R", index: 76, name: 'U 70', step: "zbll"},
  { alg: "R U R' U' R U' R' U2 R U' R' U2 R U R'", index: 77, name: 'U 62', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U' R U R' U R U2 R'", index: 78, name: 'U 63', step: "zbll"},
  { alg: "R' U' R U' R U2 R2 U' R2 U' R2 U R", index: 79, name: 'U 68', step: "zbll"},
  { alg: "R U2 R2 U' R2 U' R' U R' U' R U R' U R", index: 80, name: 'U 66', step: "zbll"},
  { alg: "R' U' R U R' U R U2 R' U R U2 R' U' R", index: 81, name: 'U 61', step: "zbll"},
  { alg: "R' U2 R U R' U R U R' U' R U' R' U2 R", index: 82, name: 'U 65', step: "zbll"},
  { alg: "R U R' U R' U2 R2 U R2 U R2 U' R'", index: 83, name: 'U 67', step: "zbll"},
  { alg: "R' U2 R2 U R2 U R U' R U R' U' R U' R'", index: 84, name: 'U 64', step: "zbll"},
  { alg: "F U R U2 R' U R U R' U R U2 R' U R U R' F'", index: 85, name: 'U 53', step: "zbll"},
  { alg: "r U R' U' M U R U' R' F R U R' U' F'", index: 86, name: 'U 54', step: "zbll"},
  { alg: "r U2 R2 F R F' U2 r' R U R U' R'", index: 87, name: 'U 55', step: "zbll"},
  { alg: "R' U2 R F U' R' U R U R' U R U' F'", index: 88, name: 'U 56', step: "zbll"},
  { alg: "R U' R' U' R U R D R' U R D' R2", index: 89, name: 'U 49', step: "zbll"},
  { alg: "R U R' L' U2 R U' R' U' R U' R' L", index: 90, name: 'U 51', step: "zbll"},
  { alg: "R2 D' R U R' D R U R U' R' U' R", index: 91, name: 'U 52', step: "zbll"},
  { alg: "F R U R' U' R U R' U' F' U' R' F' U' F U R", index: 92, name: 'U 50', step: "zbll"},
  { alg: "R2 D R' U' R D' R' U' R' U R U R'", index: 93, name: 'U 57', step: "zbll"},
  { alg: "M' U R' U' F' U F R2 U R' U R U2 r'", index: 94, name: 'U 58', step: "zbll"},
  { alg: "R' U R U R' U' R' D' R U' R' D R2", index: 95, name: 'U 59', step: "zbll"},
  { alg: "R' U' R U' F U' R' U R U R' U R U' F'", index: 96, name: 'U 60', step: "zbll"},
  { alg: "R' U' R F R2 D' R U R' D R2 U' F'", index: 97, name: 'U 30', step: "zbll"},
  { alg: "F U R2 D' R U' R' D R2 F' R' U R", index: 98, name: 'U 29', step: "zbll"},
  { alg: "R2 D' R U2 R' D R U2 R2 U R' U' R' F R2 U' R' U' R U R' F'", index: 99, name: 'U 32', step: "zbll"},
  { alg: "R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' U2 R", index: 100, name: 'U 31', step: "zbll"},
  { alg: "R2 F R U R U' R' F' R U' R2 D' R U R' D R2", index: 101, name: 'U 36', step: "zbll"},
  { alg: "r U R' U' r' F R2 U' R' U' R U2 R' U' F'", index: 102, name: 'U 35', step: "zbll"},
  { alg: "R U2 R' U2 R' F R U R U2 R' U' R U2 R' U' F'", index: 103, name: 'U 34', step: "zbll"},
  { alg: "F U R U2 R' U R U R2 F' r U R U' r'", index: 104, name: 'U 33', step: "zbll"},
  { alg: "r2 F2 r U2 r U' L' U R' U R U' L", index: 105, name: 'U 26', step: "zbll"},
  { alg: "R2 B2 R' B2 R' U R U' L U' L' U R'", index: 106, name: 'U 28', step: "zbll"},
  { alg: "F2 R U' R' U' R U R' F' R U R' U' R' F R F2", index: 107, name: 'U 27', step: "zbll"},
  { alg: "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", index: 108, name: 'U 25', step: "zbll"},
  { alg: "x R2 D2 R U2 R' D2 R U2 R x'", index: 109, name: 'U 42', step: "zbll"},
  { alg: "x' R2 D2 R' U2 R D2 R' U2 R' x", index: 110, name: 'U 41', step: "zbll"},
  { alg: "R U' R2 F R U R U' R2 F' R U' F' U F", index: 111, name: 'U 44', step: "zbll"},
  { alg: "F R U' R' U R U R' U R U' R' F'", index: 112, name: 'U 43', step: "zbll"},
  { alg: "R F U' R' U' R U2 R' U' R F' R'", index: 113, name: 'U 48', step: "zbll"},
  { alg: "R' U2 R U R' U R' D' R U' R' D R U R", index: 114, name: 'U 47', step: "zbll"},
  { alg: "R U' R' U' R U' R' U R' D' R U R' D R2 U R'", index: 115, name: 'U 46', step: "zbll"},
  { alg: "R U R' U R' D' R U2 R' D R2 U' R' U2 R U2 R'", index: 116, name: 'U 45', step: "zbll"},
  { alg: "R U R' U R U' R' U2 R' D' R U2 R' D R2 U' R'", index: 117, name: 'U 38', step: "zbll"},
  { alg: "R' U2 R U R' U R' D R' U2 R D' R' U2 R'", index: 118, name: 'U 40', step: "zbll"},
  { alg: "R' U' R U2 R' F' R U R' U' R' F R2 U2 R' U R", index: 119, name: 'U 39', step: "zbll"},
  { alg: "R U R' U R U R' U2 R U' R2 D' R U' R' D R", index: 120, name: 'U 37', step: "zbll"},
  { alg: "R' F' r U2 R' D R U' R' D' R2 U' r' F", index: 121, name: 'U 18', step: "zbll"},
  { alg: "R2 D' R U2 R' D R U2 R", index: 122, name: 'U 17', step: "zbll"},
  { alg: "F R U R' U' R2 D R' U' R D' R2 U' R U R' F'", index: 123, name: 'U 20', step: "zbll"},
  { alg: "R D r' U2 r D' R' U2 R' U R U R' U R", index: 124, name: 'U 19', step: "zbll"},
  { alg: "F U R U' R D R' U' R D' R2 U R U R' F'", index: 125, name: 'U 24', step: "zbll"},
  { alg: "R' U R U' R' U' R U2 R D R' U' R D' R2 U' R", index: 126, name: 'U 23', step: "zbll"},
  { alg: "R2 F' R U2 R U2 R' F U' R U R' U' R", index: 127, name: 'U 22', step: "zbll"},
  { alg: "R2 D' R U2 R' U' D R' U' R2 U R U R2", index: 128, name: 'U 21', step: "zbll"},
  { alg: "R2 D' R U' R' D R2 U' R' U2 R", index: 129, name: 'U 14', step: "zbll"},
  { alg: "R' U2 R' D' R U2 R' D R U2 R U R' U R", index: 130, name: 'U 16', step: "zbll"},
  { alg: "R' U R U R' U2 R U R D R' U2 R D' R'", index: 131, name: 'U 15', step: "zbll"},
  { alg: "R2 D' r U2 r' D R U2 R", index: 132, name: 'U 13', step: "zbll"},
  { alg: "R2 D R' U2 R D' R' U2 R'", index: 133, name: 'U 6', step: "zbll"},
  { alg: "R U2 R2 D' R U2 R' D R2 U' R' U2 R U2 R'", index: 134, name: 'U 5', step: "zbll"},
  { alg: "R' U' R U R U R' U' R' U F R U R U' R' F'", index: 135, name: 'U 8', step: "zbll"},
  { alg: "R' D' r U2 r' D R U2 R U' R' U' R U' R'", index: 136, name: 'U 7', step: "zbll"},
  { alg: "R U' R' U R U R' U2 R' D' R U R' D R2 U R'", index: 137, name: 'U 12', step: "zbll"},
  { alg: "R U R' U R U' R' U R U' R' U' L' U R U' R' L", index: 138, name: 'U 11', step: "zbll"},
  { alg: "R2 D' R U' R' D R2 U R' U R U2 R' U R U2 R' U' R", index: 139, name: 'U 10', step: "zbll"},
  { alg: "R U R' U R U' R' U F' R U2 R' U2 R' F R", index: 140, name: 'U 9', step: "zbll"},
  { alg: "R U2 R D R' U2 R D' R' U2 R' U' R U' R'", index: 141, name: 'U 2', step: "zbll"},
  { alg: "R U R2 D' R U R' D R2 U2 R'", index: 142, name: 'U 4', step: "zbll"},
  { alg: "R2 D r' U2 r D' R' U2 R'", index: 143, name: 'U 3', step: "zbll"},
  { alg: "R U' R' U' R U2 R' U' R' D' R U2 R' D R", index: 144, name: 'U 1', step: "zbll"},
  { alg: "R U' R' L' U2 L U L' U L R U2 R'", index: 145, name: 'L 72', step: "zbll"},
  { alg: "R U R' U R U' R' U R U' R' U R U2 R'", index: 146, name: 'L 71', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U2 R U R' U R U2 R'", index: 147, name: 'L 69', step: "zbll"},
  { alg: "R U R' U R U2 R' U2 R U2 R' U' R U' R'", index: 148, name: 'L 70', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U R' U2 R U R' U R", index: 149, name: 'L 62', step: "zbll"},
  { alg: "R U R' U R U2 R' U R' U' R U' R' U2 R", index: 150, name: 'L 63', step: "zbll"},
  { alg: "R2 U R' U' R' U R U R' U R U' R U' R2", index: 151, name: 'L 68', step: "zbll"},
  { alg: "R2 U' R U' R U R' U R U R' U' R' U R2", index: 152, name: 'L 66', step: "zbll"},
  { alg: "R2 U R' U R' U' R U' R' U' R U R U' R2", index: 153, name: 'L 61', step: "zbll"},
  { alg: "R' U2 R U R' U R U' R U2 R' U' R U' R'", index: 154, name: 'L 65', step: "zbll"},
  { alg: "R' U' R U' R' U2 R U' R U R' U R U2 R'", index: 155, name: 'L 67', step: "zbll"},
  { alg: "R2 U' R U R U' R' U' R U' R' U R' U R2", index: 156, name: 'L 64', step: "zbll"},
  { alg: "F' r U R' U R' D R U' R' D' R U' r' F R", index: 157, name: 'L 53', step: "zbll"},
  { alg: "r U R2 D' R U2 R' D R U r' F R F'", index: 158, name: 'L 54', step: "zbll"},
  { alg: "F R U R' U' R' F R2 U' R' U' R U R' F2", index: 159, name: 'L 55', step: "zbll"},
  { alg: "M' U' r U2 R' F R U2 r2 F R", index: 160, name: 'L 56', step: "zbll"},
  { alg: "r U2 r2 F R F' r2 R' U2 r'", index: 161, name: 'L 49', step: "zbll"},
  { alg: "R' D' R U' R' D R U2 R U' R' U R U R' U' R U R'", index: 162, name: 'L 51', step: "zbll"},
  { alg: "R' F2 R2 r' F' r U R2 F2 R", index: 163, name: 'L 52', step: "zbll"},
  { alg: "R U R' U R U' R' F2 R U2 R' U2 R' F2 R2 U' R' U2", index: 164, name: 'L 50', step: "zbll"},
  { alg: "R' U' R U R' F' R U R' U' R' F R2", index: 165, name: 'L 57', step: "zbll"},
  { alg: "F R U R' U' R U' R' U2 R U2 R' U' F'", index: 166, name: 'L 58', step: "zbll"},
  { alg: "L U L' U' L F L' U' L U L F' L2", index: 167, name: 'L 59', step: "zbll"},
  { alg: "R' U2 R2 U R' F' R U R' U' R' F R2 U' R' U' R' U2 R", index: 168, name: 'L 60', step: "zbll"},
  { alg: "R U R' U R U' R' U R U' R' U R2 D R' U2 R D' R2", index: 169, name: 'L 30', step: "zbll"},
  { alg: "F' r U R' U' r' F R", index: 170, name: 'L 29', step: "zbll"},
  { alg: "R U2 R' U2 D R' U R' U' R' U R2 D'", index: 171, name: 'L 32', step: "zbll"},
  { alg: "R' F R U R U' R' F' U R U R' U R U' R'", index: 172, name: 'L 31', step: "zbll"},
  { alg: "F R U' R' U' R U2 R' U' F'", index: 173, name: 'L 36', step: "zbll"},
  { alg: "R' U' R' D' R U2 R' D R U R U' R' U' R", index: 174, name: 'L 35', step: "zbll"},
  { alg: "R U R' U R' D' R U2 R' D R2 U' R' U R U' R'", index: 175, name: 'L 34', step: "zbll"},
  { alg: "F' R U2 R' U2 R' F R U R U' R'", index: 176, name: 'L 33', step: "zbll"},
  { alg: "L' U R' U' L R U2 R' U R U R' U R", index: 177, name: 'L 26', step: "zbll"},
  { alg: "F' R U2 R' U2 R' F U2 R U R U' R2 U2 R", index: 178, name: 'L 28', step: "zbll"},
  { alg: "S' R' U' R f R' F' U R U R U' R'", index: 179, name: 'L 27', step: "zbll"},
  { alg: "R' U' R U R' F2 R U2 R' U2 R' F2 R2", index: 180, name: 'L 25', step: "zbll"},
  { alg: "R U2 R' U2 R U R2 D' R U2 R' D R2 U2 R'", index: 181, name: 'L 42', step: "zbll"},
  { alg: "R U2 R D R' U2 R D' R2", index: 182, name: 'L 41', step: "zbll"},
  { alg: "R U R' U R U R' U2 R' D' r U2 r' D R", index: 183, name: 'L 44', step: "zbll"},
  { alg: "F R U R' U' R' F' U' R U R U' R' U' R' U R", index: 184, name: 'L 43', step: "zbll"},
  { alg: "F U' R U R' U R' U2 R U R' U R2 U' R' U F'", index: 185, name: 'L 48', step: "zbll"},
  { alg: "R' U R' D' R U R' U2 R U R' U D R U' R", index: 186, name: 'L 47', step: "zbll"},
  { alg: "R' F' R U2 R U2 R' F U' R U R' U' R U' R'", index: 187, name: 'L 46', step: "zbll"},
  { alg: "R U' R2 D' R U' R' D R U2 R U' R' U' R U R'", index: 188, name: 'L 45', step: "zbll"},
  { alg: "R U2 R' U' R2 D R' U' R D' R2", index: 189, name: 'L 38', step: "zbll"},
  { alg: "R U2 R D r' U2 r D' R2", index: 190, name: 'L 40', step: "zbll"},
  { alg: "R' D' R U2 R' D R U R U2 R' U R U R'", index: 191, name: 'L 39', step: "zbll"},
  { alg: "R U R' U R U2 R D R' U2 R D' R' U2 R'", index: 192, name: 'L 37', step: "zbll"},
  { alg: "F R' F' r U R U' r'", index: 193, name: 'L 18', step: "zbll"},
  { alg: "R' U' R U' R' U R U' R' U R U' R2 D' R U2 R' D R2", index: 194, name: 'L 17', step: "zbll"},
  { alg: "L R U' R' U L' R U R' U R U' R'", index: 195, name: 'L 20', step: "zbll"},
  { alg: "x' r U r' D' F r U r' F' D r U2 L'", index: 196, name: 'L 19', step: "zbll"},
  { alg: "R U R' F' U' r' F2 r U F", index: 197, name: 'L 24', step: "zbll"},
  { alg: "F R U R' U' R' F' R U2 R U2 R'", index: 198, name: 'L 23', step: "zbll"},
  { alg: "R U' R' U' R' D' r U2 r' D R U' R U R'", index: 199, name: 'L 22', step: "zbll"},
  { alg: "R U R D R' U2 R D' R' U' R' U R U R'", index: 200, name: 'L 21', step: "zbll"},
  { alg: "R U' R' U R U' R' U' R U R2 D' R U' R' D R", index: 201, name: 'L 14', step: "zbll"},
  { alg: "R' U2 R2 U R' U' R' U2 F R U R U' R' F'", index: 202, name: 'L 16', step: "zbll"},
  { alg: "R' U2 R F U' R' U2 R U F' U' R' U R", index: 203, name: 'L 15', step: "zbll"},
  { alg: "R2 D r' U2 M' U' R D' R' U' R'", index: 204, name: 'L 13', step: "zbll"},
  { alg: "R' U2 R' D' R U2 R' D R2", index: 205, name: 'L 6', step: "zbll"},
  { alg: "F' r U R2 D R U R' D' R U2 r' F R", index: 206, name: 'L 5', step: "zbll"},
  { alg: "F R U' R' U R U R2 D' R U R' D R2 U' R' F'", index: 207, name: 'L 8', step: "zbll"},
  { alg: "R' U' R U' R' U' R U2 R D r' U2 r D' R'", index: 208, name: 'L 7', step: "zbll"},
  { alg: "F R U' R' U' R2 D R' U R D' R' U R' U' F'", index: 209, name: 'L 12', step: "zbll"},
  { alg: "R' U R2 D R' U R D' R' U2 R' U R U R' U' R", index: 210, name: 'L 11', step: "zbll"},
  { alg: "R' U R U' R' U F' R U2 R' U2 R' F R2", index: 211, name: 'L 10', step: "zbll"},
  { alg: "R' U' R2 D r' U2 r D' R2 U R U R' U2 R", index: 212, name: 'L 9', step: "zbll"},
  { alg: "R D R' U2 R D' R' U' R' U2 R U' R' U' R", index: 213, name: 'L 2', step: "zbll"},
  { alg: "R' U2 R' D' r U2 r' D R2", index: 214, name: 'L 4', step: "zbll"},
  { alg: "R' U2 R U R2 D' R U R' D R2", index: 215, name: 'L 3', step: "zbll"},
  { alg: "F' R U R' U' R' F R2 U' R' U' R U' R' U R U R'", index: 216, name: 'L 1', step: "zbll"},
  { alg: "R U R2 U' R2 U' R2 U2 R2 U' R' U R U2 R'", index: 217, name: 'Pi 72', step: "zbll"},
  { alg: "R U R' U R U2 R' U R U R' U R U2 R'", index: 218, name: 'Pi 71', step: "zbll"},
  { alg: "R' U' R U R U2 R' U' R U' R2 U2 R", index: 219, name: 'Pi 69', step: "zbll"},
  { alg: "R U R' U' R' U2 R U R' U R2 U2 R'", index: 220, name: 'Pi 70', step: "zbll"},
  { alg: "R U R' U R U2 R2 U2 R U R' U R", index: 221, name: 'Pi 62', step: "zbll"},
  { alg: "R U2 R' U2 R U' R' U2 R U' R' U2 R U R'", index: 222, name: 'Pi 63', step: "zbll"},
  { alg: "R' U2 R2 U R2 U R2 U2 R'", index: 223, name: 'Pi 68', step: "zbll"},
  { alg: "R' U R U2 R' U' R U2 R' U' R U2 R' U2 R", index: 224, name: 'Pi 66', step: "zbll"},
  { alg: "R U2 R2 U' R2 U' R2 U2 R", index: 225, name: 'Pi 61', step: "zbll"},
  { alg: "R U' R' U2 R U R' U2 R U R' U2 R U2 R'", index: 226, name: 'Pi 65', step: "zbll"},
  { alg: "R U2 R' U' R U' R2 U' R U' R' U2 R", index: 227, name: 'Pi 67', step: "zbll"},
  { alg: "R' U2 R U2 R' U R U2 R' U R U2 R' U' R", index: 228, name: 'Pi 64', step: "zbll"},
  { alg: "F U R' U' R2 U' R2 U2 R U2 R U R' F'", index: 229, name: 'Pi 53', step: "zbll"},
  { alg: "R' U' R' D' R U R' D R U2 R' D' R U2 R' D R2", index: 230, name: 'Pi 54', step: "zbll"},
  { alg: "R2 D R' U' R D' R' U' R' U R U' R' U' R U' R'", index: 231, name: 'Pi 55', step: "zbll"},
  { alg: "R2 D' R U R' D R U R U' R' U R U R' U R", index: 232, name: 'Pi 56', step: "zbll"},
  { alg: "R U2 R' U2 R' U' F U R2 U' R' U R U' R' F'", index: 233, name: 'Pi 49', step: "zbll"},
  { alg: "R F U' R2 U2 R U R' U R2 U F' R'", index: 234, name: 'Pi 51', step: "zbll"},
  { alg: "R U R' U' R U R2 D' R U' R' D R U' R U2 R'", index: 235, name: 'Pi 52', step: "zbll"},
  { alg: "R U R' F' R U R' U R U2 R' F U R U2 R'", index: 236, name: 'Pi 50', step: "zbll"},
  { alg: "R U2 R' U R' D' R U R' D R2 U' R' U R U' R'", index: 237, name: 'Pi 57', step: "zbll"},
  { alg: "R2 D R' U2 R D' R2 U' R U R D R' U2 R D' R2", index: 238, name: 'Pi 58', step: "zbll"},
  { alg: "R' U' R U R' U' R2 D R' U R D' R' U R' U2 R", index: 239, name: 'Pi 59', step: "zbll"},
  { alg: "R U2 R' U' F' R U2 R' U' R U' R' F R U' R'", index: 240, name: 'Pi 60', step: "zbll"},
  { alg: "L' U' L U L F' L2 U' L U L' U' L U F", index: 241, name: 'Pi 30', step: "zbll"},
  { alg: "F U R U2 R' U2 R U R2 F' R U2 R U2 R'", index: 242, name: 'Pi 29', step: "zbll"},
  { alg: "R' D' R U R' D R U2 R U2 R' U R U' R' U' R U' R'", index: 243, name: 'Pi 32', step: "zbll"},
  { alg: "R U R' U' R U R2 D' R U R' D R U R U' R' U R U2 R'", index: 244, name: 'Pi 31', step: "zbll"},
  { alg: "L' U' L U' L' U2 L U L' U R U' L U R'", index: 245, name: 'Pi 36', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U2 r' F R F' r U R'", index: 246, name: 'Pi 35', step: "zbll"},
  { alg: "R' U' R U' R' U R U' R' U R' D' R U R' D R2", index: 247, name: 'Pi 34', step: "zbll"},
  { alg: "r' F R F' r U R' U R U2 R' U' R U' R'", index: 248, name: 'Pi 33', step: "zbll"},
  { alg: "L F' L' U' L U L F L2 U L U' L' U L U2 L'", index: 249, name: 'Pi 26', step: "zbll"},
  { alg: "R' U2 R U R' U' R U R2 F R U R U' R' F' R", index: 250, name: 'Pi 28', step: "zbll"},
  { alg: "F' U' L U L' F U L U' L' U L U2 L' U", index: 251, name: 'Pi 27', step: "zbll"},
  { alg: "R' U' R' D' R U' R' D R2 U R' U' R U R' U R", index: 252, name: 'Pi 25', step: "zbll"},
  { alg: "R' U' R' D' R U' D R' D' R U2 R' D R D' R' D R2", index: 253, name: 'Pi 42', step: "zbll"},
  { alg: "R U R' U' R' F R2 U R' U' R U R' U' F'", index: 254, name: 'Pi 41', step: "zbll"},
  { alg: "F U R U' R' S R' D' R U R' D R2 U' R' f'", index: 255, name: 'Pi 44', step: "zbll"},
  { alg: "R U2 R' U' R U R' U' R' D' R U' R' D R2 U' R' U R U' R'", index: 256, name: 'Pi 43', step: "zbll"},
  { alg: "R U R' U F2 R U2 R' U2 R' F2 R", index: 257, name: 'Pi 48', step: "zbll"},
  { alg: "R U R' U R U' R' U R U' R D R' U' R D' R2", index: 258, name: 'Pi 47', step: "zbll"},
  { alg: "R2 D' R U' R' D R U' R U R' U' R U R' U R", index: 259, name: 'Pi 46', step: "zbll"},
  { alg: "R U R' U R U2 R' U' R U' L' U R' U' L", index: 260, name: 'Pi 45', step: "zbll"},
  { alg: "R U R D R' U R D' R2 U' R U R' U' R U' R'", index: 261, name: 'Pi 38', step: "zbll"},
  { alg: "R' U' R U' R' U R U' R2 D' R U R' D R U R", index: 262, name: 'Pi 40', step: "zbll"},
  { alg: "R2 F2 R2 U' R U R' U R2 F2 R' U2 R'", index: 263, name: 'Pi 39', step: "zbll"},
  { alg: "R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R", index: 264, name: 'Pi 37', step: "zbll"},
  { alg: "R U2 R' U' R U2 R' U2 R U' R2 D' R U' R' D R", index: 265, name: 'Pi 18', step: "zbll"},
  { alg: "R' U' R U R2 F' R U R U' R' F U' R U R' U R", index: 266, name: 'Pi 17', step: "zbll"},
  { alg: "R U2 R' U' R U r' F2 r U2 R' U' r' F r", index: 267, name: 'Pi 20', step: "zbll"},
  { alg: "F U R U2 R' U R U R' F' R U2 R' U' R U' R'", index: 268, name: 'Pi 19', step: "zbll"},
  { alg: "R U R' U F' R U2 R' U2 R' F R", index: 269, name: 'Pi 24', step: "zbll"},
  { alg: "r U' r' U' r U r' F R' F' R2 U' R'", index: 270, name: 'Pi 23', step: "zbll"},
  { alg: "r' U r U r' U' r U R2 F R F' R", index: 271, name: 'Pi 22', step: "zbll"},
  { alg: "L' U R U' L U' R' U' R U' R'", index: 272, name: 'Pi 21', step: "zbll"},
  { alg: "R2 D R' U2 R D' R2 U' R2 D R' U' R D' R2", index: 273, name: 'Pi 14', step: "zbll"},
  { alg: "R U R' U R2 D R' U' R D' R2 U R U2 R'", index: 274, name: 'Pi 16', step: "zbll"},
  { alg: "R' U' R U' R2 D' R U R' D R2 U' R' U2 R", index: 275, name: 'Pi 15', step: "zbll"},
  { alg: "R2 D' R U2 R' D R2 U R2 D' R U R' D R2", index: 276, name: 'Pi 13', step: "zbll"},
  { alg: "F R U R' U' R' F' R U2 R' U' R2 U' R2 U2 R", index: 277, name: 'Pi 6', step: "zbll"},
  { alg: "F R' F' R U2 R U2 R' U' r U R' U R U2 r'", index: 278, name: 'Pi 5', step: "zbll"},
  { alg: "F U R U' R' U R U2 R' U' R U R' F'", index: 279, name: 'Pi 8', step: "zbll"},
  { alg: "R2 F R U R U' R' F' R U' R' U' R U R' U R", index: 280, name: 'Pi 7', step: "zbll"},
  { alg: "R' U' F' R U R' U' R' F R2 U2 R' U2 R", index: 281, name: 'Pi 12', step: "zbll"},
  { alg: "R F U R2 U2 R2 U R2 U R2 F' R'", index: 282, name: 'Pi 11', step: "zbll"},
  { alg: "F U' R U' R' U R U R' U2 R U2 R' U F'", index: 283, name: 'Pi 10', step: "zbll"},
  { alg: "R U R' U R U' R' U' R' F' R U2 R U2 R' F", index: 284, name: 'Pi 9', step: "zbll"},
  { alg: "r' F' r U' r' F2 r2 U R' U' r' F R F'", index: 285, name: 'Pi 2', step: "zbll"},
  { alg: "R U R D R' U' R D' R U' R U' R' U2 R", index: 286, name: 'Pi 4', step: "zbll"},
  { alg: "R' U' R' D' R U R' D R3 U R' U R U2 R'", index: 287, name: 'Pi 3', step: "zbll"},
  { alg: "R U R' U R U2 R2 F' r U R U' r' F", index: 288, name: 'Pi 1', step: "zbll"},
  { alg: "R U R' U R U' R' U R U' R' U R' U' R2 U' R' U R' U R", index: 289, name: 'H 40', step: "zbll"},
  { alg: "R U R' U R U2 R' U' R' U2 R U R' U R", index: 290, name: 'H 39', step: "zbll"},
  { alg: "R U2 R' U' R U' R' U' R' U' R U' R' U2 R", index: 291, name: 'H 38', step: "zbll"},
  { alg: "R' U2 R U R' U R U R U R' U R U2 R'", index: 292, name: 'H 37', step: "zbll"},
  { alg: "R' U' R U' R' U R U' R' U2 R", index: 293, name: 'H 34', step: "zbll"},
  { alg: "R U2 R' U' R U R' U' R U' R'", index: 294, name: 'H 36', step: "zbll"},
  { alg: "R U R' U R U' R' U R U2 R'", index: 295, name: 'H 33', step: "zbll"},
  { alg: "R' U2 R U R' U' R U R' U R", index: 296, name: 'H 35', step: "zbll"},
  { alg: "x' U' R U' R' U R' F2 R U' R U R' U x", index: 297, name: 'H 28', step: "zbll"},
  { alg: "F R U R' U' R U R' U' R U R' U' F'", index: 298, name: 'H 27', step: "zbll"},
  { alg: "R' U2 R U R' U R U' r U2 R2 F R F' R U2 r'", index: 299, name: 'H 29', step: "zbll"},
  { alg: "R' F2 r2 U' r' F r' F2 R2 U R' U R U2 R'", index: 300, name: 'H 30', step: "zbll"},
  { alg: "R' U' F' U F R U f R U R' U' R U R' U' f'", index: 301, name: 'H 31', step: "zbll"},
  { alg: "R U R' U y' R' U R U' R2 F R F' R", index: 302, name: 'H 32', step: "zbll"},
  { alg: "r U2 R2 F R F' R U2 r' L' U2 L U L' U L", index: 303, name: 'H 26', step: "zbll"},
  { alg: "F' U' F U2 R2 U R2 U R2 U2 R2 F' U F", index: 304, name: 'H 25', step: "zbll"},
  { alg: "R U2 R' U' R U R' U' F' R U R' U' R' F R2 U' R'", index: 305, name: 'H 6', step: "zbll"},
  { alg: "R' U2 R2 U R2 U R U2 R' F R U R U' R' F'", index: 306, name: 'H 5', step: "zbll"},
  { alg: "R' U' R U' R' U R U R' F R U R' U' R' F' R2", index: 307, name: 'H 7', step: "zbll"},
  { alg: "F R U' R' U R U2 R' U' R U R' U' F'", index: 308, name: 'H 8', step: "zbll"},
  { alg: "f R2 S' U' R2 U' R2 U R2 F'", index: 309, name: 'H 11', step: "zbll"},
  { alg: "R' U2 R U2 R2 F' R U R U' R' F U R", index: 310, name: 'H 10', step: "zbll"},
  { alg: "R F R2 U' R2 U' R2 U2 R2 U' F' R'", index: 311, name: 'H 9', step: "zbll"},
  { alg: "R D' R U2 R' U2 R U' R' U' R U R' D R'", index: 312, name: 'H 12', step: "zbll"},
  { alg: "F' r U R' U' r' F R2 U2 R' U' R U' R'", index: 313, name: 'H 1', step: "zbll"},
  { alg: "F R' F' r U R U' r2 F2 r U L' U L", index: 314, name: 'H 2', step: "zbll"},
  { alg: "R' D R2 U' R2 D' R U' R' D R2 U2 R2 D' R", index: 315, name: 'H 4', step: "zbll"},
  { alg: "R U2 R' U' R U R' U2 R' F R2 U' R' U' R U R' F'", index: 316, name: 'H 3', step: "zbll"},
  { alg: "R' U' R U' R' U F' R U R' U' R' F R2 U' R' U R", index: 317, name: 'H 18', step: "zbll"},
  { alg: "R' D' R U R' D R2 U R' U2 R U2 R' U R U2 R'", index: 318, name: 'H 17', step: "zbll"},
  { alg: "R' U' R D' R U' R' U2 R U2 R U R U' R2 D", index: 319, name: 'H 19', step: "zbll"},
  { alg: "R U R' U R U2 R' F R U' R' U' R U2 R' U' F'", index: 320, name: 'H 20', step: "zbll"},
  { alg: "R' F R' F' R2 U' r' U r U' r' U' r", index: 321, name: 'H 23', step: "zbll"},
  { alg: "R U R' U R U r' F R' F' r", index: 322, name: 'H 22', step: "zbll"},
  { alg: "R' U' R U' R' U' L U' R U L'", index: 323, name: 'H 21', step: "zbll"},
  { alg: "R U R2 F R F' r U' r' U r U r'", index: 324, name: 'H 24', step: "zbll"},
  { alg: "R2 D R' U R D' R2 U R2 D R' U2 R D' R2", index: 325, name: 'H 13', step: "zbll"},
  { alg: "R U2 R' U' R2 D R' U R D' R2 U' R U' R'", index: 326, name: 'H 14', step: "zbll"},
  { alg: "R' U2 R U R2 D' R U' R' D R2 U R' U R", index: 327, name: 'H 16', step: "zbll"},
  { alg: "R2 D' R U' R' D R2 U' R2 D' R U2 R' D R2", index: 328, name: 'H 15', step: "zbll"},
  { alg: "R U R' U' R U R' U R U R U2 R' U' R U' R' U R'", index: 329, name: 'S 72', step: "zbll"},
  { alg: "R' U2 R2 U R2 U R U' R U' R'", index: 330, name: 'S 71', step: "zbll"},
  { alg: "R U R' U' R' U2 R U R U' R' U R' U R", index: 331, name: 'S 69', step: "zbll"},
  { alg: "R' F' U' F U R F U R U' R' F'", index: 332, name: 'S 70', step: "zbll"},
  { alg: "R' U2 R2 U2 R2 U' R2 U' R2 U R", index: 333, name: 'S 68', step: "zbll"},
  { alg: "R U R2 F' R U2 R U' R' U' R' F R2 U' R'", index: 334, name: 'S 66', step: "zbll"},
  { alg: "R U R' U R U' R' U R' U' R2 U' R' U R' U R", index: 335, name: 'S 62', step: "zbll"},
  { alg: "R U R2 U' R2 U' R2 U2 R2 U2 R'", index: 336, name: 'S 63', step: "zbll"},
  { alg: "R U R' U R U2 R'", index: 337, name: 'S 67', step: "zbll"},
  { alg: "R' U2 R U R' U R", index: 338, name: 'S 64', step: "zbll"},
  { alg: "R U R' U' R' U2 R U R' U R U' R U' R'", index: 339, name: 'S 61', step: "zbll"},
  { alg: "R' U' R U' R U R' U R U2 R' U' R' U R", index: 340, name: 'S 65', step: "zbll"},
  { alg: "R' U' F U R U' R' F' R2 U R' U' R' F R F'", index: 341, name: 'S 53', step: "zbll"},
  { alg: "R U R2 F2 R U2 R U2 R' F2 U R U2 R'", index: 342, name: 'S 54', step: "zbll"},
  { alg: "R' U2 R U R' U' R F U' R' U' R U F'", index: 343, name: 'S 55', step: "zbll"},
  { alg: "L' U2 R U' R' U2 L U R U' R' U R U2 R'", index: 344, name: 'S 56', step: "zbll"},
  { alg: "F' R U R' D R U R' U' D' R U' R' F", index: 345, name: 'S 52', step: "zbll"},
  { alg: "F U R' F R F' R U' R' U R U' R' F'", index: 346, name: 'S 50', step: "zbll"},
  { alg: "R2 U R2 F' R U2 R' U' R U' R' F R2 U' R2", index: 347, name: 'S 49', step: "zbll"},
  { alg: "R U' R2 U2 D' R U R' U D R2 U R'", index: 348, name: 'S 51', step: "zbll"},
  { alg: "R' F R f' U R U R' U2 f R' F' R", index: 349, name: 'S 59', step: "zbll"},
  { alg: "F R U' R2 U2 R U R' U R2 U R' F'", index: 350, name: 'S 60', step: "zbll"},
  { alg: "R U R' U L' U R U' L U2 R'", index: 351, name: 'S 57', step: "zbll"},
  { alg: "F U' R' U R U F' R U R2 U R2 U2 R'", index: 352, name: 'S 58', step: "zbll"},
  { alg: "F R' U' R2 U' R2 U2 F R F' R U' R' F'", index: 353, name: 'S 42', step: "zbll"},
  { alg: "F R U R' U' R' F' R U R2 D R' U' R D' R2", index: 354, name: 'S 41', step: "zbll"},
  { alg: "F U R U' R' S R' F' R U R U' R' S'", index: 355, name: 'S 44', step: "zbll"},
  { alg: "R2 D' r U2 r' D R2 U R' U R", index: 356, name: 'S 43', step: "zbll"},
  { alg: "R' U2 R U R' U R' D' R U2 R' D R U2 R", index: 357, name: 'S 46', step: "zbll"},
  { alg: "F R U R' U' R' F' R U2 R U' R' U R U2 R'", index: 358, name: 'S 45', step: "zbll"},
  { alg: "R2 D' R U2 R' D R2 U R' U R", index: 359, name: 'S 48', step: "zbll"},
  { alg: "R2 F R U R U' R' F' R U' R' U R", index: 360, name: 'S 47', step: "zbll"},
  { alg: "R' U2 R U R2 D' R U' R' D R U2 R", index: 361, name: 'S 39', step: "zbll"},
  { alg: "r' R F R' F' r U2 R U2 R'", index: 362, name: 'S 37', step: "zbll"},
  { alg: "R' D' R U R' D R2 U R' U2 R U R'", index: 363, name: 'S 38', step: "zbll"},
  { alg: "f R' F' R U2 R U2 R' U2 S'", index: 364, name: 'S 40', step: "zbll"},
  { alg: "R U R' U R U' R' U' D R2 U' R U' R' U R' U R2 D'", index: 365, name: 'S 30', step: "zbll"},
  { alg: "R U' r' F R' F' r", index: 366, name: 'S 29', step: "zbll"},
  { alg: "R U R' F' R U R' U R U' R' U' R' F R2 U' R'", index: 367, name: 'S 32', step: "zbll"},
  { alg: "R' U2 R U R' U' R U2 R' F R U R' U' R' F' R2", index: 368, name: 'S 31', step: "zbll"},
  { alg: "R U R' U R U' R' U' R' F R2 U' R' U' R U R' F'", index: 369, name: 'S 34', step: "zbll"},
  { alg: "R' U' R' U R2 D' U2 R U R' U' D R'", index: 370, name: 'S 33', step: "zbll"},
  { alg: "R' U' D R' U R D' U2 R2 U R' U' R'", index: 371, name: 'S 36', step: "zbll"},
  { alg: "R2 D r' U2 r D' R' U' R' U R U2 R'", index: 372, name: 'S 35', step: "zbll"},
  { alg: "R' U2 R U R' U' R' D' R U2 R' D R2", index: 373, name: 'S 27', step: "zbll"},
  { alg: "R2 D R' U2 R D' R' U' R' U R U2 R'", index: 374, name: 'S 25', step: "zbll"},
  { alg: "R' U2 F' R U R' U' R' F R U2 R", index: 375, name: 'S 26', step: "zbll"},
  { alg: "L U2 L F L' U' L' U L F' U2 L'", index: 376, name: 'S 28', step: "zbll"},
  { alg: "F' R U R' U R U2 R' F U R U' R' U2 R U' R'", index: 377, name: 'S 6', step: "zbll"},
  { alg: "R' F R U R' U' R' F' D' R U R' D R2", index: 378, name: 'S 5', step: "zbll"},
  { alg: "R U R' U R2 D r' U2 r D' R2", index: 379, name: 'S 8', step: "zbll"},
  { alg: "R' U' R U R2 U' R' U' R U D' R U R' D R'", index: 380, name: 'S 7', step: "zbll"},
  { alg: "R U R' U R2 D R' U2 R D' R2", index: 381, name: 'S 10', step: "zbll"},
  { alg: "R U R' U' R U R2 D' R U R' D R U R U2 R'", index: 382, name: 'S 9', step: "zbll"},
  { alg: "R U2 R D R' U2 R D' R' U R' U R U2 R'", index: 383, name: 'S 12', step: "zbll"},
  { alg: "R U R2 F' R U2 R U2 R' F R U' R'", index: 384, name: 'S 11', step: "zbll"},
  { alg: "R' U R U2 R' U R2 D R' U R D' R'", index: 385, name: 'S 3', step: "zbll"},
  { alg: "R' U2 R U F R' U R U' F'", index: 386, name: 'S 1', step: "zbll"},
  { alg: "R U R' U R U' R2 F' R U R U' R' F R U' R'", index: 387, name: 'S 2', step: "zbll"},
  { alg: "S' U2 L' U2 L U2 L F' L' f", index: 388, name: 'S 4', step: "zbll"},
  { alg: "x D R2 D2 R U2 R' D2 R U2 R D'", index: 389, name: 'S 18', step: "zbll"},
  { alg: "F R' U R U F' R' U F U F' R", index: 390, name: 'S 17', step: "zbll"},
  { alg: "R U' R' U' R U R D R' U2 R D' R2 U R U2 R'", index: 391, name: 'S 20', step: "zbll"},
  { alg: "R U R' U R U' R D R' U R r' U2 r D' R2", index: 392, name: 'S 19', step: "zbll"},
  { alg: "R U R' U R U' R D R' U R D' R' U2 R'", index: 393, name: 'S 22', step: "zbll"},
  { alg: "R' U2 R' D' R U R' D R U' R U R' U R", index: 394, name: 'S 21', step: "zbll"},
  { alg: "R2 D' R U' R' D R U' R U R' U R", index: 395, name: 'S 24', step: "zbll"},
  { alg: "R U R' U R U' R D R' U' R D' R2", index: 396, name: 'S 23', step: "zbll"},
  { alg: "R' U' R U' R2 F' R U R U' R' F U2 R", index: 397, name: 'S 15', step: "zbll"},
  { alg: "F R U' R' U R U2 R2 F R F' R' F R F' U' F'", index: 398, name: 'S 13', step: "zbll"},
  { alg: "F U R U' R' U R U' l U' R2 D' R U R'", index: 399, name: 'S 14', step: "zbll"},
  { alg: "R U2 R' U' R U R' U' R U R D R' U2 R D' R2", index: 400, name: 'S 16', step: "zbll"},
  { alg: "R2 D' R U2 R' D R U R' F R U R U' R' F' R", index: 401, name: 'AS 72', step: "zbll"},
  { alg: "R U R' U R' U' R2 U' R2 U2 R", index: 402, name: 'AS 71', step: "zbll"},
  { alg: "R U R' U' R' U' R U R U' R' U' R' U R", index: 403, name: 'AS 69', step: "zbll"},
  { alg: "R' U' R U R U2 R' U' R' U R U' R U' R'", index: 404, name: 'AS 70', step: "zbll"},
  { alg: "R' U' R U' R' U2 R", index: 405, name: 'AS 68', step: "zbll"},
  { alg: "R U2 R' U' R U' R'", index: 406, name: 'AS 66', step: "zbll"},
  { alg: "R' U' R U R U2 R' U' R U' R' U R' U R", index: 407, name: 'AS 62', step: "zbll"},
  { alg: "R U R' U R' U' R U' R' U2 R U R U' R'", index: 408, name: 'AS 63', step: "zbll"},
  { alg: "R U2 R2 U2 R2 U R2 U R2 U' R'", index: 409, name: 'AS 67', step: "zbll"},
  { alg: "R' U' R U' R U R2 U R U' R U R' U' R U' R'", index: 410, name: 'AS 64', step: "zbll"},
  { alg: "R2 U R2 U R' U2 R' U R U R' U' R2", index: 411, name: 'AS 61', step: "zbll"},
  { alg: "R' U' R2 U R2 U R2 U2 R2 U2 R", index: 412, name: 'AS 65', step: "zbll"},
  { alg: "F R' F' R U R U' R2 F R U R' U' F' U R", index: 413, name: 'AS 53', step: "zbll"},
  { alg: "F' U2 R' D R U' R' D' R f R' F R f'", index: 414, name: 'AS 54', step: "zbll"},
  { alg: "F U' R' U R U F' R' U R U' R' U2 R", index: 415, name: 'AS 55', step: "zbll"},
  { alg: "R' F' U' F U R F R U R' U' R U R' U' F'", index: 416, name: 'AS 56', step: "zbll"},
  { alg: "R' F R f' U2 R U' R' U' f R' F' R", index: 417, name: 'AS 52', step: "zbll"},
  { alg: "R U2 R2 U' R2 U' R' F U' R' U' R U F'", index: 418, name: 'AS 50', step: "zbll"},
  { alg: "R U' R' F' R U R' U' R' F R2 U' R' U2 R U' R'", index: 419, name: 'AS 49', step: "zbll"},
  { alg: "R U R' F' R U2 R' U' R U' R' F R U' R'", index: 420, name: 'AS 51', step: "zbll"},
  { alg: "R' U F' R U R' U' R' F R U2 R U2 R' U' R", index: 421, name: 'AS 59', step: "zbll"},
  { alg: "R U' R2 D' U' R U' R' U2 D R2 U R'", index: 422, name: 'AS 60', step: "zbll"},
  { alg: "R2 U R2 F' R U R' U R U2 R' F R2 U' R2", index: 423, name: 'AS 57', step: "zbll"},
  { alg: "F R U R' U' R U R' F R' F' R U' F'", index: 424, name: 'AS 58', step: "zbll"},
  { alg: "R2 D' R U' R' D F R U R U' R' F' R", index: 425, name: 'AS 42', step: "zbll"},
  { alg: "R2 D R' U2 R D' R U' R2 U' R' U R' U R", index: 426, name: 'AS 41', step: "zbll"},
  { alg: "R U R' U R U' R2 F R F' r U' r' U r U r'", index: 427, name: 'AS 44', step: "zbll"},
  { alg: "R2 D r' U2 r D' R2 U' R U' R'", index: 428, name: 'AS 43', step: "zbll"},
  { alg: "R' U' R U' R' F' R U R' U' R' F R U R U' R' U2 R", index: 429, name: 'AS 46', step: "zbll"},
  { alg: "R U2 R' U' R U' R D R' U2 R D' R' U2 R'", index: 430, name: 'AS 45', step: "zbll"},
  { alg: "F R U R2 U2 R2 U R2 U R F'", index: 431, name: 'AS 48', step: "zbll"},
  { alg: "R2 D R' U2 R D' R2 U' R U' R'", index: 432, name: 'AS 47', step: "zbll"},
  { alg: "L' R U' L U R' U2 L' U2 L", index: 433, name: 'AS 39', step: "zbll"},
  { alg: "R U R' F' R U R' U' R' F R2 U R' U' R U' R'", index: 434, name: 'AS 37', step: "zbll"},
  { alg: "f' L F L' U2 L' U2 L U2 S", index: 435, name: 'AS 38', step: "zbll"},
  { alg: "R D R' U' R D' R2 U' R U2 R' U' R", index: 436, name: 'AS 40', step: "zbll"},
  { alg: "r' F R F' r U R'", index: 437, name: 'AS 30', step: "zbll"},
  { alg: "R' U2 R U R2 D' R U' R' D R2 U R' U' R U R' U R", index: 438, name: 'AS 29', step: "zbll"},
  { alg: "D R' U' R D' R U' R' U R2 U R' U' R2", index: 439, name: 'AS 32', step: "zbll"},
  { alg: "R' U R U R' U' R' D' R U R' D R U R U' R' U2 R", index: 440, name: 'AS 31', step: "zbll"},
  { alg: "R U R U' R2 D U2 R' U' R U D' R", index: 441, name: 'AS 34', step: "zbll"},
  { alg: "R' U2 R' D' R U R' D R U' R U R' U' R U R' U R", index: 442, name: 'AS 33', step: "zbll"},
  { alg: "F R U' R' U R U R2 F' R U R U R' U' R U' R'", index: 443, name: 'AS 36', step: "zbll"},
  { alg: "R D' U R U' R' U2 D R2 U' R U R", index: 444, name: 'AS 35', step: "zbll"},
  { alg: "R2 D' R U2 R' D R U R U' R' U2 R", index: 445, name: 'AS 27', step: "zbll"},
  { alg: "R U2 R' U' R U R D R' U2 R D' R2", index: 446, name: 'AS 25', step: "zbll"},
  { alg: "R' U2 R' F' R U R U' R' F U2 R", index: 447, name: 'AS 26', step: "zbll"},
  { alg: "F U R U' R' U R U' R2 F' R U2 R U2 R'", index: 448, name: 'AS 28', step: "zbll"},
  { alg: "R' F U' F' U' R F U' R' U' R F' U", index: 449, name: 'AS 6', step: "zbll"},
  { alg: "R' F U2 R' D' R U2 R' D R F' R", index: 450, name: 'AS 5', step: "zbll"},
  { alg: "R2 F' R2 U R2 D' F' U' D F' U F2 R2", index: 451, name: 'AS 8', step: "zbll"},
  { alg: "R' U' R U' R' U R' D' R U' R' r U2 r' D R2", index: 452, name: 'AS 7', step: "zbll"},
  { alg: "R U2 R' U R' D' R U' R' D R U' R U' R'", index: 453, name: 'AS 10', step: "zbll"},
  { alg: "R U R D' R' U2 R D R' D' R' U2 R U' D R'", index: 454, name: 'AS 9', step: "zbll"},
  { alg: "R' U' R U' R' U R' D' R U R' D R2", index: 455, name: 'AS 12', step: "zbll"},
  { alg: "R U R' U' D R' U' R U R2 U' R U R2 D'", index: 456, name: 'AS 11', step: "zbll"},
  { alg: "D R2 U' R U' R2 U R' U R2 D' R U2 R'", index: 457, name: 'AS 3', step: "zbll"},
  { alg: "R U R2 F' U' F U R F R' F' R2 U2 R'", index: 458, name: 'AS 1', step: "zbll"},
  { alg: "R' U2 F' R U R' U' R' F R2 U R' U R", index: 459, name: 'AS 2', step: "zbll"},
  { alg: "R' U2 R' U2 F' R U R U' R' F R' U2 R U2 R", index: 460, name: 'AS 4', step: "zbll"},
  { alg: "F2 D F' U F D' F2 R' F U' F' U R", index: 461, name: 'AS 18', step: "zbll"},
  { alg: "F R U R' F R' F' U2 R2 U R2 U R F'", index: 462, name: 'AS 17', step: "zbll"},
  { alg: "R D' R U' R D R' U R2 D' R U2 D R' U2 R", index: 463, name: 'AS 20', step: "zbll"},
  { alg: "F R' F' U2 R U F' R' U R U F R U' R'", index: 464, name: 'AS 19', step: "zbll"},
  { alg: "R U2 R' U' R U R' U2 R' F R U R U' R' F'", index: 465, name: 'AS 22', step: "zbll"},
  { alg: "R' U' R U' R2 D' R U2 R' D R2", index: 466, name: 'AS 21', step: "zbll"},
  { alg: "R' U' R U R' F R U R' U' R' F' R2", index: 467, name: 'AS 24', step: "zbll"},
  { alg: "R' U2 R' D' R U2 R' D R U' R U' R' U2 R", index: 468, name: 'AS 23', step: "zbll"},
  { alg: "F U2 F' U' R' F U' F' U R", index: 469, name: 'AS 15', step: "zbll"},
  { alg: "R U' R' U2 R U' R2 D' R U' R' D R", index: 470, name: 'AS 13', step: "zbll"},
  { alg: "R U2 R' U' F' R U R' U' R' F R2 U' R'", index: 471, name: 'AS 14', step: "zbll"},
  { alg: "R' U2 R' D' R U R' D R2 U' R' U2 R", index: 472, name: 'AS 16', step: "zbll"}
];
