  
import type { Case } from './LLpatternBuilder';

/**
 * Development only file for building the patterns.json files.
 */
export const ollCases: Case[] = [
  { alg: "R U2 R2 F R F' U2 R' F R F'", index: 1, name: '1', step: "oll"},
  { alg: "R U' R2 D' r U r' D R2 U R'", index: 2, name: '2', step: "oll"},
  { alg: "f R U R' U' f' U' F R U R' U' F'", index: 3, name: '3', step: "oll"},
  { alg: "f R U R' U' f' U F R U R' U' F'", index: 4, name: '4', step: "oll"},
  { alg: "l' U2 L U L' U l", index: 5, name: '5', step: "oll"},
  { alg: "r U2 R' U' R U' r'", index: 6, name: '6', step: "oll"},
  { alg: "r U R' U R U2 r'", index: 7, name: '7', step: "oll"},
  { alg: "l' U' L U' L' U2 l", index: 8, name: '8', step: "oll"},
  { alg: "R U R' U' R' F R2 U R' U' F'", index: 9, name: '9', step: "oll"},
  { alg: "R U R' U R' F R F' R U2 R'", index: 10, name: '10', step: "oll"},
  { alg: "r' R2 U R' U R U2 R' U M'", index: 11, name: '11', step: "oll"},
  { alg: "r R2 U' R U' R' U2 R U' r' R", index: 12, name: '12', step: "oll"},
  { alg: "F U R U2 R' U' R U R' F'", index: 13, name: '13', step: "oll"},
  { alg: "R' F R U R' F' R F U' F'", index: 14, name: '14', step: "oll"},
  { alg: "r' U' r R' U' R U r' U r", index: 15, name: '15', step: "oll"},
  { alg: "r U r' R U R' U' r U' r'", index: 16, name: '16', step: "oll"},
  { alg: "R U R' U R' F R F' U2 R' F R F'", index: 17, name: '17', step: "oll"},
  { alg: "R U2 R2 F R F' U2 M' U R U' r'", index: 18, name: '18', step: "oll"},
  { alg: "S' R U R' S U' R' F R F'", index: 19, name: '19', step: "oll"},
  { alg: "r U R' U' M2 U R U' R' U' M'", index: 20, name: '20', step: "oll"},
  { alg: "R U2 R' U' R U R' U' R U' R'", index: 21, name: '21', step: "oll"},
  { alg: "R U2 R2 U' R2 U' R2 U2 R", index: 22, name: '22', step: "oll"},
  { alg: "R2 D' R U2 R' D R U2 R", index: 23, name: '23', step: "oll"},
  { alg: "r U R' U' r' F R F'", index: 24, name: '24', step: "oll"},
  { alg: "F R' F' r U R U' r'", index: 25, name: '25', step: "oll"},
  { alg: "R' U' R U' R' U2 R", index: 26, name: '26', step: "oll"},
  { alg: "R U R' U R U2 R'", index: 27, name: '27', step: "oll"},
  { alg: "r U R' U' r' R U R U' R'", index: 28, name: '28', step: "oll"},
  { alg: "R U R' U' R U' R' F' U' F R U R'", index: 29, name: '29', step: "oll"},
  { alg: "F U R U2 R' U' R U2 R' U' F'", index: 30, name: '30', step: "oll"},
  { alg: "R' U' F U R U' R' F' R", index: 31, name: '31', step: "oll"},
  { alg: "S R U R' U' R' F R f'", index: 32, name: '32', step: "oll"},
  { alg: "R U R' U' R' F R F'", index: 33, name: '33', step: "oll"},
  { alg: "R U R2 U' R' F R U R U' F'", index: 34, name: '34', step: "oll"},
  { alg: "R U2 R2 F R F' R U2 R'", index: 35, name: '35', step: "oll"},
  { alg: "L' U' L U' L' U L U L F' L' F", index: 36, name: '36', step: "oll"},
  { alg: "F R U' R' U' R U R' F'", index: 37, name: '37', step: "oll"},
  { alg: "R U R' U R U' R' U' R' F R F'", index: 38, name: '38', step: "oll"},
  { alg: "L F' L' U' L U F U' L'", index: 39, name: '39', step: "oll"},
  { alg: "R' F R U R' U' F' U R", index: 40, name: '40', step: "oll"},
  { alg: "R U R' U R U2 R' F R U R' U' F'", index: 41, name: '41', step: "oll"},
  { alg: "R' U' R U' R' U2 R F R U R' U' F'", index: 42, name: '42', step: "oll"},
  { alg: "R' U' F' U F R", index: 43, name: '43', step: "oll"},
  { alg: "F U R U' R' F'", index: 44, name: '44', step: "oll"},
  { alg: "F R U R' U' F'", index: 45, name: '45', step: "oll"},
  { alg: "R' U' R' F R F' U R", index: 46, name: '46', step: "oll"},
  { alg: "F R' F' R U2 R U' R' U R U2 R'", index: 47, name: '47', step: "oll"},
  { alg: "F R U R' U' R U R' U' F'", index: 48, name: '48', step: "oll"},
  { alg: "r U' r2 U r2 U r2 U' r", index: 49, name: '49', step: "oll"},
  { alg: "l' U l2 U' l2 U' l2 U l'", index: 50, name: '50', step: "oll"},
  { alg: "F U R U' R' U R U' R' F'", index: 51, name: '51', step: "oll"},
  { alg: "R U R' U R U' B U' B' R'", index: 52, name: '52', step: "oll"},
  { alg: "l' U' L U' L' U L U' L' U2 l", index: 53, name: '53', step: "oll"},
  { alg: "r U2 R' U' R U R' U' R U' r'", index: 54, name: '54', step: "oll"},
  { alg: "R' F R U R U' R2 F' R2 U' R' U R U R'", index: 55, name: '55', step: "oll"},
  { alg: "r U r' U R U' R' U R U' R' r U' r'", index: 56, name: '56', step: "oll"},
  { alg: "R U R' U' M' U R U' r'", index: 57, name: '57', step: "oll"},
 ];

export const pllCases: Case[] = [
  { alg: "x R' U R' D2 R U' R' D2 R2", index: 1, name: 'Aa', step: "pll"},
  { alg: "x R2 D2 R U R' D2 R U' R", index: 2, name: 'Ab', step: "pll"},
  { alg: "x' R U' R' D R U R' D' R U R' D R U' R' D'", index: 3, name: 'E', step: "pll"},
  { alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", index: 4, name: 'F', step: "pll"},
  { alg: "R2 U R' U R' U' R U' R2 D U' R' U R D'", index: 5, name: 'Ga', step: "pll"},
  { alg: "R' U' R D' U R2 U R' U R U' R U' R2 D", index: 6, name: 'Gb', step: "pll"},
  { alg: "R2 F2 R U2 R U2 R' F R U R' U' R' F R2", index: 7, name: 'Gc', step: "pll"},
  { alg: "R U R' D U' R2 U' R U' R' U R' U R2 D'", index: 8, name: 'Gd', step: "pll"},
  { alg: "M2 U M2 U2 M2 U M2", index: 9, name: 'H', step: "pll"},
  { alg: "R' U L' U2 R U' R' U2 R L", index: 10, name: 'Ja', step: "pll"},
  { alg: "R U R' F' R U R' U' R' F R2 U' R'", index: 11, name: 'Jb', step: "pll"},
  { alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'", index: 12, name: 'Na', step: "pll"},
  { alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R", index: 13, name: 'Nb', step: "pll"},
  { alg: "R U' R' U' R U R D R' U' R D' R' U2 R'", index: 14, name: 'Ra', step: "pll"},
  { alg: "R' U2 R' D' R U' R' D R U R U' R' U' R", index: 15, name: 'Rb', step: "pll"},
  { alg: "R U R' U' R' F R2 U' R' U' R U R' F'", index: 16, name: 'T', step: "pll"},
  { alg: "R U R' U R' U' R2 U' R' U R' U R", index: 17, name: 'Ua', step: "pll"},
  { alg: "R' U R' U' R3 U' R' U R U R2", index: 18, name: 'Ub', step: "pll"},
  { alg: "R' U R' d' R' F' R2 U' R' U R' F R F", index: 19, name: 'V', step: "pll"},
  { alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'", index: 20, name: 'Y', step: "pll"},
  { alg: "M' U' M2 U' M2 U' M' U2 M2", index: 21, name: 'Z', step: "pll"}
];