export const notimerTaglines: string[] = [
  "It was never about the times",
  "It was always about the times",
  "Take a break",
  "Well, here we are",
  "Chill",
  "Correlate",
  "Gather",
  "Feel it out",
  "Can't do it all",
  "Just do a few",
  "Put the phone away",
  "Just sit there",
  "See the stickers again",
  "Let go of the bad",
  "Go slow",
  "Figure it all out",
  "Live wild, be free",
  "A better kind of scrolling",
  "Forever tabbing forward",
  "Space out",
  "Not another timer",
  "Notimer",
  "Untimer",
  "ZenTimer",
  "An experience",
  "Nothing like it",
  "A time unending",
  "Keep it simple",
  "Keep it 50/50",
  "Give me zen",
  "A journey of a million spaces",
  "The cool of rain on skin",
  "The pinpricking of stars",
  "A slow carousel",
  "Fall into new patterns",
  "One more time",
]
