type Step = 'oll' | 'pll' | 'zbll' | 'eo' | 'onelll' | 'f2l';
//todo: get a text file I can just paste in all the algs into, and then a script to parse them into this

export interface ExactAlg {
  value: string;
  add_y: boolean;
  add_U: boolean;
  name?: string;
  step: Step;
}

export interface LastLayerAlg {
  value: string;
  step: Step;
}

export interface ZBLSalg extends LastLayerAlg {
  eoIndex: number;
}

/**
 * For cases where piece starting locations are exact.
 * For example, f2l cases require corner and edges to be in a precise spot and with a certain orientation.
 */
export const rawGeneric: ExactAlg[] = [ 
  { value: "R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R' f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' L f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' L' f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' R' U R U r' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U2 R2 U R2' U r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U2' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U' L' U2 L U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U' R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U2 R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' U' F' U F R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' U' L' U L2 f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F2 r2 B r2 F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L2 U L2 U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U2' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L U2' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R' U2' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U R' U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U2 F' U' F U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U2 L' U' L U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' B U' B' U2' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' F' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "M' U R U' r' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "d' R U' R' U R U R' U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U' R' U R f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "M U R' U' R U R' U2' r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' S R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R' f' U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R' U R' U' R2 f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R U2' R' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U R D R' U' R D' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S' R' U' R S R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' y U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "d' L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U' R' U R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U M' U R U' r' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R2 U2' R2' F' R2 U2' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U' R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R' U2 R U' R' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' U f R' f' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R S R' S' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R U R' U' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U2 R2 U' R2 U' r' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U R2' U' R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R2' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2' R2' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U2' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "l' U L U L' U' l", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F r U r' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L2 U' L2 U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R' F R F' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' L' U L U' L' U2 L F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U R U R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D' R U' R' D R U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S' R U R' S R U2' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' F R F' R U2' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U2' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R2' U R U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' S' R U2' R' S R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U L U L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U2 F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U2 R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R2' F R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L' U2 L U' L' U L U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' F R F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U' F R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' F R F' U' R' F R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2' R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2' R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r B U' r B r2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2 R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L F' L' F L' U L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U2 R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L U L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U2' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R' F R F2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R' F R F2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L2 F' L' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B' R B R2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B U2' B' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R2' F R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' r' U2 r U r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' L' U2 L F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' F R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y r' U r' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' D' R U2 R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' R U' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' F R F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' D' R U R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U r U2' r' U' r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f U R U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F' U2' F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R' F' R2 U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F' r U' r' F2 U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F' U' F2 R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U R U2' R2' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' r B r2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "l U' l' U2 l U l'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' L U' L' U L U' L' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U R' U R U2 B r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U r' F' r2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R' U R U2' R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' R U R' U' R' F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U' F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R S' R' U' R S R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R S' R' U2' R S R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' F R' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' S' R U' R' S R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' S' R U R' S R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' S' R U2 R' S R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R S2 R' U' R S2 R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R U R U' R' U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' E2 R U R' E2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R E' R' U R E R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' r U r' U' r' F r F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R U R U' R' U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' E R U R' E' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' F' R U R' U' R' F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U r' U' r' F r F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' R' F R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f U R2' U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R' F R F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U2' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2' R' F R F2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' L F L2' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U' F R' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' R U' R' U R U' R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' U2' F R2 F' U2' R' U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' R' U2' R2 U2 R2' U R U2' R' F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' R' U2 R2 U R2' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R f R U R2' U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R F R U R2' U' R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U R f R U R2' U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R2 U2 F R2 F' U2 R' U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' F R F' R U' R' U R U' R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' R U R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2 U2' R' U' R U' R' U2 R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' r' U2 r U r' R U R' U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' r' F2 r F R U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' R' U2 R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' F' U' F U R U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U L U2' L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U R' U' F' U F R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U' R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U2 L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U R2' F R F2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' F U R U' R' F2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U2 R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R U R' U R U2' R2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' r U' r' U2 r U r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R' U' R U2 R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' U f R2' U2' R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U' R' r U' r' U2 r U r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' L U2 L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U2' R' U R U2' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U L' U' L U2 L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F2' R' F' R2 U' R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' F' U2' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R' F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U2' F R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2 U R2' U R2 U2' R2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U L' U' L U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R f' U' f R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R2 f' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R f R2 f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R' F R F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R' U R U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U R' U' R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L F' L' F L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' L U L' U' L U L' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L F' L' F L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L' U L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L' U L2 F' L' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L2 U' L2' U' L2 U2 L2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' L U' L' U L' f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' F R' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "M' U R U' r' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D R' U R D' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D R' U' R D' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D R' U2 R D' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2' R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2' F' U2' F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R' U R' U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R U R U' R2' f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R f' U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U f' L' f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D R U' R' D' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D R U R' D' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D R U2 R' D' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U2' R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F R F' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D' R U' R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D' R U R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D' R U2 R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L D' L' U' L D L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L D' L' U L D L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L D' L' U2' L D L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U L' U L U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' B U2' B' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U' F U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U' F U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U2' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R' F' R U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D' R' U' R D R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D R' U R D R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R D' R' U R D R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U2' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' L' f U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U2' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L F' L F L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U F U' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U' F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U R' U2' R F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L R U2 R' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R2 U R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' U2' R U2 R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' R U' R' U R U' R' L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U2 L' U2 L U2 L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' U' R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U L' U L U' L U L' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' R U' R' U2 L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' R' U R U' R' U' R F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' R U R' L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R2 U' R' U' R U R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U' R U' R' U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' y R' U' R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' L' U' L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R U' R' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R U' R' U2 F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R B' U B", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R L' U2 L2 U L2 U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R F U' R U2 R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R2 U2 R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U L U L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R F U2 R U R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' R U R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' R' U R U' R' U' R F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' R' U R F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U L U' L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R F U' R U' R' U' R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R2 U R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R U' R' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R' U' R L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R U' R' U2 F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L2 U2 L U2 L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 r' U2 R2 U R2' U r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' R U2 R2' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U F U' R U2 R' U R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' F U R U' R' F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U R2' U2 R U R' U R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' F R U' R' L' U' L U L F' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' R U2 R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' R' U R F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U L' U' L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' R U' R' U2 F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' R' U' R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 R U' R' U F' L' U2 L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U F U2 R U' R' L' U' L U r U' r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' F U' F' R U R' U' R' F R2 U R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' R U' R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U' R' U' L U L' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L F R' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R2 U R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L R' U2 R2 U R2 U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U2 R2' U' R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L2 U2 L' U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L R' D' R U' R' D R U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U' R2' F R F' R U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L U L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U' R U R2' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U2 f R f' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U L U L' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U' R' U2 F' U' F R' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U' R' U R' U' R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' S R f' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L2 U L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U' R' U R U R2' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' R' U' R U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U' R' U' L U L' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R2' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' R' U' R F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B' U' B R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' F U2' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S R S' R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R F' R' U' R F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R F U F' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U f R S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F2 R F2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r2 U B2 U' r2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R2 U' R' U2 F' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L F' U F L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U2 L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R2 U2 R' U R U R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y F' R' U' R F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U F U2 R U R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2 R' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U2 L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R2 U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' F R F' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r2' U' F2 U r2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' R' U R F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' L U2 L' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U F U' F' U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L2 U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U F U' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2 R F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' R U' R' U2 F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' R' U2 R U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' F U2 R U R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' R U2 R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' R' U2 R U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L2 U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' L U2 L' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F R F' R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U L U2 L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R' U2 R U R' U' R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U' R' F U2' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2 R U R2 F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U F' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F L U L' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L R U2 R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L2 U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U L' U' L F' U' F U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U L' U' L U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R' U L U L' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U' R2' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F U' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L2 U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S R' S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U2 F U' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R S R' f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U2 F U' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S U R U' R S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R U R' U2 R U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R' U f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R2' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B' U2 B R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R U R U R' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U' f R S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U2 L U L' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' F U2 R U R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U f' L f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' U L' U' L2 f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' y R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' L U' L' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F U2 F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R y R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' F R S R' f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U2 F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R f' U2 L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U2 F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R2' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R L' U2 L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S R S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R F U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U2 R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R' U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R' U' R U L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R2 U2 R' U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S' L' S", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B' U2 B R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L2 U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L2' U2 L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U2 F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L2' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U' F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U F U2 R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' R U2 R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R U2 R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' y' R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R L' U' L R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U F2 U' r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L f R' f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L2 U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U2 y' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R2' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U2 f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U2' S R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U2 F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U R' U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' f R' f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L R U' R' U2 F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' R' U' R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U2 y' L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U' F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' R' U R U r' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L F' U2 F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' F' U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U2 F U R U' R' F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U2 R2 U R2' U r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U2 R2 U R2' U r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U2' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R2 U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R2 U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2' R2 U R2 U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U' R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L U2 R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R U R' U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' U2 L' U' L U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' F' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U2 F' U' F U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' B U' B' U2' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "M' U R U' r' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U2 R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R' U2 R U' R' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U F' U' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U R' F R F' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "S' R U R' S R U2' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' D' R U' R' D R U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' U2 R U R' U' R U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R2' F R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' U R U' R' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F' R' U2 R U F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B' R B R2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R2' F R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R B U2' B' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R' F R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' r' U2 r U r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y r' U r' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R2' D' R U2 R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' D' R U R' D R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' F' R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U R' U2 R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' U' F' U F R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U R' U R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "d' R U' R' U R U R' U'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "M U R' U' R U R' U2' r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R U' R' U R f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' S R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "M' U' r' U F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R U2' R' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R U R' U' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U R2' U' R F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U2 R2 U' R2 U' r' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R2' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U R U2' f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' S' R U2' R' S R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' F R F' R U2' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f R2' U R U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2' R' U' R U R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2' R' U R U' R' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U r U2' r' U' r", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f U R U' R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F' U2' F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R' F' R f R f'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2' R' U' S R' S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R' F' R2 U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F' r U' r' F2 U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F' U' F2 R' F' R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U' R' U' S R' S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2' U2' R U R' U R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R F' U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R2 U2' R U R' U R2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U S R2' S'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "f' U' L' U L2 f", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U2 R' r U R' U R U2 B r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F2 r2 B r2 F R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2' R U R' U2' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L2 U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R U R' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L2 U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L2 U L2 U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R U2 L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' y U2 R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U R' U' F' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U L' U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U' L U2 L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U' R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R U2' R2' U' R2 U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U R U' R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L F L' U2 L U L' U L F' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U L U L' U L U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U' L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2' R U R' U' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r B U' r B r2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L' U L U' L' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y R' U2 R U' R' U R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U' r B r2'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U2 L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "l U' l' U2 l U l'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U' L' U' L U' L' U L U' L' U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r U R' U R U2 B r'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U2' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U' R L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L U2' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' U2 R L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R' U2' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "d' L U' L' U L U L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U' R' U R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U M' U R U' r' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F R2 U2' R2' F' R2 U2' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U' R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U2' R' U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "l' U L U L' U' l", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "R' F r U r' F' R", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U R U' R' U2 F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L U2 L2 U' L2 U' L'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U' L' U' L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U L U2 F U F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L F' L' F L' U L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L U L' U' L U", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "y' R U2' R' U R U' R'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U2 L2 F' L' F", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "L' U' L U' L' U L", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "r' U r' F' r2", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U R' U R U2' R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
  { value: "F U' R U2 R' U R U2 R' F'", name: "", add_y: false, add_U: true, step: "f2l"},
];

export const rawOLLalgs: LastLayerAlg[] = [
  { value: "R U2 R2 F R F' U2 R' F R F'", step: 'oll'},
  { value: "R U' R2 D' r U' r' D R2 U R'", step: 'oll'},
  { value: "R U' R2 D' r U r' D R2 U R'", step: 'oll'},
  { value: "F R U R' U' S R U R' U' f'", step: 'oll'},
  { value: "F R U R' U' F' U2 F U R U' R' F'", step: 'oll'},
  { value: "R U' r' R' r R' D' r U r' D R2 U R'", step: 'oll'},
  { value: "f R U R' U' f' U' F R U R' U' F'", step: 'oll'},
  { value: "L' l U l' U2 l U L' U L M'", step: 'oll'},
  { value: "R' F2 R2 U2 R' F R U2 R2 F2 R", step: 'oll'},
  { value: "f R U R' U' f' R' F' U' F U R", step: 'oll'},
  { value: "f R U R' U' f' U F R U R' U' F'", step: 'oll'},
  { value: "F U R U' R' F' U' F R U R' U' F'", step: 'oll'},
  { value: "f R U R' U' y x R' F R U R' U' F'", step: 'oll'},
  { value: "f R U R' d' x R' F R U R' U' F'", step: 'oll'},
  { value: "f R U R' d' x R' F R U R' U' f' S", step: 'oll'},
  { value: "l' U2 L U L' U l", step: 'oll'},
  { value: "r' U2 R U R' U r", step: 'oll'},
  { value: "F R R' F' l' U2 L U L' U l", step: 'oll'},
  { value: "R' F2 r U r' F R", step: 'oll'},
  { value: "r' U2 R U R2 R U r", step: 'oll'},
  { value: "r U2 R' U' R U' r'", step: 'oll'},
  { value: "U r U2 R' U' R U' r'", step: 'oll'},
  { value: "y U r U2 R' U' R U' r'", step: 'oll'},
  { value: "r U R' U R U2 r'", step: 'oll'},
  { value: "U' r U R' U R U2 r'", step: 'oll'},
  { value: "r U R' U R U' U' r'", step: 'oll'},
  { value: "r U R' U r U2 U2 r' R U2 r'", step: 'oll'},
  { value: "l' U' L U' L' U2 l", step: 'oll'},
  { value: "r' U' R U' R' U2 r", step: 'oll'},
  { value: "R' F' r U' r' F2 R", step: 'oll'},
  { value: "R R' U' r' U' R U' R' U2 r", step: 'oll'},
  { value: "R U2 R' U2 R' F R F'", step: 'oll'},
  { value: "R U R' U' R' F R2 U R' U' F'", step: 'oll'},
  { value: "F F' R U R' U' R' F R2 U R' U' F'", step: 'oll'},
  { value: "L' U' L U' L F' L' F L' U2 L", step: 'oll'},
  { value: "R' U' R y' x' R U' R' F R U l'", step: 'oll'},
  { value: "R U R' U R' F R F' R U2 R'", step: 'oll'},
  { value: "R U R' y R' F R U' R' F' R", step: 'oll'},
  { value: "F U F' R' F R U' R' F' R", step: 'oll'},
  { value: "L U L' y' R' F R U' R' F' R", step: 'oll'},
  { value: "L U L' x' z L' U L F' L' U' r", step: 'oll'},
  { value: "r' R2 U R' U R U2 R' U M'", step: 'oll'},
  { value: "r U R' U R' F R F' R U2 r'", step: 'oll'},
  { value: "F F' U2 r' R2 U R' U R U2 R' U M'", step: 'oll'},
  { value: "l' L2 U L' U L U2 L' U L' l", step: 'oll'},
  { value: "r' R2 R' R U R' U R U2 R' U M'", step: 'oll'},
  { value: "r R2 U' R U' R' U2 R U' r' R", step: 'oll'},
  { value: "R' M' U' R U' R' U2 R U' r' R", step: 'oll'},
  { value: "R' M' U' R U' R' U2 R U' R r'", step: 'oll'},
  { value: "r R2 U' R U' R' U2 R U' R r'", step: 'oll'},
  { value: "l L2 U' L U' L' U2 L U' L l'", step: 'oll'},
  { value: "F U R U2 R' U' R U R' F'", step: 'oll'},
  { value: "F U R U' R2 F' R U R U' R'", step: 'oll'},
  { value: "r U' r' U' r U r' F' U F", step: 'oll'},
  { value: "r U' r' U' r U r' y' R' U R", step: 'oll'},
  { value: "x' R U' R' F' R U R' U' F U x", step: 'oll'},
  { value: "R' F R U R' F' R F U' F'", step: 'oll'},
  { value: "R' F R U R' F' R y' R U' R'", step: 'oll'},
  { value: "F F' R R2 F R U R' F' R y' R U' R'", step: 'oll'},
  { value: "R' F R l' l U l' U' l y' R U' R'", step: 'oll'},
  { value: "l' U l U l' U' l y' R U' R'", step: 'oll'},
  { value: "r' U' r R' U' R U r' U r", step: 'oll'},
  { value: "l' U' l L' U' L U l' U l", step: 'oll'},
  { value: "r' U' M' U' R U r' U r", step: 'oll'},
  { value: "l' U' L' l U' L U l' U l", step: 'oll'},
  { value: "l' l U l' U' l L' U' L U l' U l", step: 'oll'},
  { value: "r U r' R U R' U' r U' r'", step: 'oll'},
  { value: "R' F R U R' U' F' R U' R' U2 R", step: 'oll'},
  { value: "R R' r U r' R U R' U' r U' r'", step: 'oll'},
  { value: "r U U' U r' R U R' U' r U' r'", step: 'oll'},
  { value: "R U R' U R' F R F' U2 R' F R F'", step: 'oll'},
  { value: "F R' F' R2 r' U R U' R' U' M'", step: 'oll'},
  { value: "F R' F' R U2 R U' B U' B' R'", step: 'oll'},
  { value: "F R' F' R U S' R U' R' S", step: 'oll'},
  { value: "r U' r' F U2 F U' R U' R' F'", step: 'oll'},
  { value: "R U2 R2 F R F' U2 M' U R U' r'", step: 'oll'},
  { value: "R U R2 F' U' F U R U2 R' F R F'", step: 'oll'},
  { value: "R y R U R' d R' U2 R' F R F'", step: 'oll'},
  { value: "r U R' U R U2 r2 U' R U' R' U2 r", step: 'oll'},
  { value: "M U R U R' U' r R2 F R F'", step: 'oll'},
  { value: "S' R U R' S U' R' F R F'", step: 'oll'},
  { value: "r' R U R U R' U' r R2 F R F'", step: 'oll'},
  { value: "L' l U R U R' U' M' R' F R F'", step: 'oll'},
  { value: "l L' U R U R' U' r R2 F R F'", step: 'oll'},
  { value: "r' R U R U R' U' r M' R' U R U' r'", step: 'oll'},
  { value: "r U R' U' M2 U R U' R' U' M'", step: 'oll'},
  { value: "R U2 R' U' R U R' U' R U' R'", step: 'oll'},
  { value: "R U R' U R U' R' U R U2 R'", step: 'oll'},
  { value: "R U R' U R U L' U R' U' L", step: 'oll'},
  { value: "F R U' R' U R U2 R' U' R U R' U' F'", step: 'oll'},
  { value: "F R U R' U' R U R' U' R U R' U' F'", step: 'oll'},
  { value: "R U2 R2 U' R2 U' R2 U2 R", step: 'oll'},
  { value: "F U R U' R' U R U2 R' U' R U R' F'", step: 'oll'},
  { value: "R U R' U' R' F R2 U R' U' R U R' U' F'", step: 'oll'},
  { value: "F U R U' R' U R U' R2 F' R U R U' R'", step: 'oll'},
  { value: "F U R U2 R' U R U R' F' R U2 R' U' R U' R'", step: 'oll'},
  { value: "R2 D' R U2 R' D R U2 R", step: 'oll'},
  { value: "R2 D R' U2 R D' R' U2 R'", step: 'oll'},
  { value: "F R U' R' U R U R' U R U' R' F'", step: 'oll'},
  { value: "R' U2 R U R' U R' D' R U' R' D R U R", step: 'oll'},
  { value: "R' U R U R' U2 R D' U' R U' R' U2 R U' R' D", step: 'oll'},
  { value: "r U R' U' r' F R F'", step: 'oll'},
  { value: "l' U' L U l F' L' F", step: 'oll'},
  { value: "l' U' L U R U' r' F", step: 'oll'},
  { value: "R' U' R' D' R U R' D R U2 R U R' U R", step: 'oll'},
  { value: "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'", step: 'oll'},
  { value: "F R' F' r U R U' r'", step: 'oll'},
  { value: "F' r U R' U' r' F R", step: 'oll'},
  { value: "R U2 R D R' U2 R D' R2", step: 'oll'},
  { value: "R' U2 R' D' r U2 r' D R2", step: 'oll'},
  { value: "R2 D' R U' R' D R U R", step: 'oll'},
  { value: "R' U' R U' R' U2 R", step: 'oll'},
  { value: "R U2 R' U' R U' R'", step: 'oll'},
  { value: "L' U' L U' L' U2 L", step: 'oll'},
  { value: "R' U' R U' R' U' U' R", step: 'oll'},
  { value: "U R D R' U' R D' R2 U' R U2 R' U' R", step: 'oll'},
  { value: "R U R' U R U2 R'", step: 'oll'},
  { value: "R' U2 R U R' U R", step: 'oll'},
  { value: "R U' L' U R' U' L", step: 'oll'},
  { value: "R U R' U R U' U' R'", step: 'oll'},
  { value: "F R' U2 R F' R' F U2 F' R", step: 'oll'},
  { value: "r U R' U' r' R U R U' R'", step: 'oll'},
  { value: "r U R' U' M U R U' R'", step: 'oll'},
  { value: "r U R' U' R r' U R U' R'", step: 'oll'},
  { value: "M' U M U2 M' U M", step: 'oll'},
  { value: "r' U' R U M' U' R' U R", step: 'oll'},
  { value: "R U R' U' R U' R' F' U' F R U R'", step: 'oll'},
  { value: "r2 D' r U r' D r2 U' r' U' r", step: 'oll'},
  { value: "U R U R' U' R U' R' F' U' F R U R'", step: 'oll'},
  { value: "L F R' F R F2 L2 U' L U' L' U2 L", step: 'oll'},
  { value: "R' U' R U' R' U2 F R U R' U' F' U R", step: 'oll'},
  { value: "F U R U2 R' U' R U2 R' U' F'", step: 'oll'},
  { value: "r' D' r U' r' D r2 U' r' U r U r'", step: 'oll'},
  { value: "F R' F R2 U' R' U' R U R' F2", step: 'oll'},
  { value: "F U2 U' R U2 R' U' R U2 R' U' F'", step: 'oll'},
  { value: "F U R U2 R' U' R U R' R U R' U' F'", step: 'oll'},
  { value: "R' U' F U R U' R' F' R", step: 'oll'},
  { value: "U R' U' F U R U' R' F' R", step: 'oll'},
  { value: "R' R U' F R' F' R U R U R' U' R U' R'", step: 'oll'},
  { value: "R R' U' R' U' F U R U' R' F' R", step: 'oll'},
  { value: "S' L' U' L U L F' L' f", step: 'oll'},
  { value: "S R U R' U' R' F R f'", step: 'oll'},
  { value: "L U F' U' L' U L F L'", step: 'oll'},
  { value: "R U B' U' R' U R B R'", step: 'oll'},
  { value: "F U R U' F' r U R' U' r'", step: 'oll'},
  { value: "f F' R U R' U' R' F R f'", step: 'oll'},
  { value: "R U R' U' R' F R F'", step: 'oll'},
  { value: "F R U' R' U R U R' F'", step: 'oll'},
  { value: "L' U' L U L F' L' F", step: 'oll'},
  { value: "R U R2 U' R' F R U R U' F'", step: 'oll'},
  { value: "R U R' d' l' U' L U L' l", step: 'oll'},
  { value: "R U R' d' l' U' L U r' R", step: 'oll'},
  { value: "f R f' U' r' U' R U M'", step: 'oll'},
  { value: "F' U' F U r U R' U' r' R", step: 'oll'},
  { value: "R U2 R2 F R F' R U2 R'", step: 'oll'},
  { value: "L' U2 L2 F' L' F L' U2 L", step: 'oll'},
  { value: "R' U2 R l U' R' U l' U2 R", step: 'oll'},
  { value: "R U' R2 R2 U' R2 F R F' R U2 R'", step: 'oll'},
  { value: "R U2 R' y U' R' F R U' R' F' R", step: 'oll'},
  { value: "L' U' L U' L' U L U L F' L' F", step: 'oll'},
  { value: "R U R' F' R U R' U' R' F R U' R' F R F'", step: 'oll'},
  { value: "L' U' L U' L' U L U L F' L' f f' F", step: 'oll'},
  { value: "L' U' L U' L' U L U r U' r' F", step: 'oll'},
  { value: "R' F' U' F2 U R U' R' F' R", step: 'oll'},
  { value: "F R U' R' U' R U R' F'", step: 'oll'},
  { value: "F R' F' R U R U' R'", step: 'oll'},
  { value: "F' L F L' U' L' U L", step: 'oll'},
  { value: "F R U2 U R' U' R U R' F'", step: 'oll'},
  { value: "F R' R2 U' R' U' R U R' F'", step: 'oll'},
  { value: "R U R' U R U' R' U' R' F R F'", step: 'oll'},
  { value: "R U R' U R U' R2 R U' R' F R F'", step: 'oll'},
  { value: "U' R U R' U R U' R' U' R' F R F'", step: 'oll'},
  { value: "r r' R U R' U R U' R' U' R' F R F'", step: 'oll'},
  { value: "L F' L' U' L U F U' L'", step: 'oll'},
  { value: "R U R' F' U' F U R U2 R'", step: 'oll'},
  { value: "f' r U r' U' r' F r S", step: 'oll'},
  { value: "L F' L' U' L U F2 F' U' L'", step: 'oll'},
  { value: "L F' L' U' L d R U' F'", step: 'oll'},
  { value: "R' F R U R' U' F' U R", step: 'oll'},
  { value: "F R U R' U' F' R U R' U R U2 R'", step: 'oll'},
  { value: "R' F F' R U2 R' F R U R' U' F' U R", step: 'oll'},
  { value: "R U R' F' U' F R U R' U' R U' R'", step: 'oll'},
  { value: "R U R' U R U2 R' F R U R' U' F'", step: 'oll'},
  { value: "F F' R U R' U R U2 R' F R U R' U' F'", step: 'oll'},
  { value: "F U R2 D R' U' R D' R2 F'", step: 'oll'},
  { value: "F U R U' R' F' U R U' r' F R' F' r", step: 'oll'},
  { value: "F U R U' R' F' U R U R' U R U2 R'", step: 'oll'},
  { value: "R' U' R U' R' U2 R F R U R' U' F'", step: 'oll'},
  { value: "R' U' R U' R' U2 R U R' F' U' F U R", step: 'oll'},
  { value: "R' F R F' R' F R F' R U R' U' R U R'", step: 'oll'},
  { value: "F R' F' R U2 R' U' R2 U' R2 U2 R", step: 'oll'},
  { value: "F S' R U R' U' F' U S", step: 'oll'},
  { value: "R' U' F' U F R", step: 'oll'},
  { value: "F' U' L' U L F", step: 'oll'},
  { value: "R' R U' R' U' F' U F R", step: 'oll'},
  { value: "R' U' F R' F' R U R", step: 'oll'},
  { value: "U R' U' F' U F R", step: 'oll'},
  { value: "F U R U' R' F'", step: 'oll'},
  { value: "f R U R' U' f'", step: 'oll'},
  { value: "S F R U R' U' f'", step: 'oll'},
  { value: "S R R' F R U R' U' f'", step: 'oll'},
  { value: "F U R U' R' F'", step: 'oll'},
  { value: "F R U R' U' F'", step: 'oll'},
  { value: "R' F' U' F U R", step: 'oll'},
  { value: "R' R F R U R' U' F'", step: 'oll'},
  { value: "R' U' R' F R F' U R", step: 'oll'},
  { value: "R' F F' R U R' U' R' F R F' U R", step: 'oll'},
  { value: "R2 R U' R' F R F' U R", step: 'oll'},
  { value: "U' R' U' R' F R F' U R", step: 'oll'},
  { value: "U R' U' R' F R F' U R", step: 'oll'},
  { value: "F R' F' R U2 R U' R' U R U2 R'", step: 'oll'},
  { value: "R' U' R' F R F' R' F R F' U R", step: 'oll'},
  { value: "F' L' U' L U L' U' L U F", step: 'oll'},
  { value: "R' F' U' F U F' U' F U R", step: 'oll'},
  { value: "F U R U' R' F' R U' L' U R' U' L", step: 'oll'},
  { value: "F R U R' U' R U R' U' F'", step: 'oll'},
  { value: "R' U' F' U F R2 U2 R' U' R U' R'", step: 'oll'},
  { value: "F R U R' U' R2 D R' U R D' R2 U' F'", step: 'oll'},
  { value: "R U2 R' U' R U R' U2 R' F R F'", step: 'oll'},
  { value: "U' F R U R' U' R U R' U' F'", step: 'oll'},
  { value: "r U' r2 U r2 U r2 U' r", step: 'oll'},
  { value: "l U' l2 U l2 U l2 U' l", step: 'oll'},
  { value: "r r' U r U' r2 U r2 U r2 U' r", step: 'oll'},
  { value: "R' U2 R U R' U R F R U R' U' F'", step: 'oll'},
  { value: "r r' U' R U2 R' U' R U' R' U' R' U' F' U F R", step: 'oll'},
  { value: "l' U l2 U' l2 U' l2 U l'", step: 'oll'},
  { value: "r' U r2 U' r2 U' r2 U r'", step: 'oll'},
  { value: "R' F R2 B' R2 F' R2 B R'", step: 'oll'},
  { value: "l' U l2 U' l2 l2 l2 U' l2 U l'", step: 'oll'},
  { value: "l' U l2 U' l2 l2 U U' l2 l2 l2 U' l2 U l'", step: 'oll'},
  { value: "F U R U' R' U R U' R' F'", step: 'oll'},
  { value: "f R U R' U' R U R' U' f'", step: 'oll'},
  { value: "F' U' L' U L U' L' U L F", step: 'oll'},
  { value: "R' F F' R U' R' U' F' U F U' F' U F R", step: 'oll'},
  { value: "R U R' U R U' B U' B' R'", step: 'oll'},
  { value: "R' F' U' F U' R U R' U R", step: 'oll'},
  { value: "F R U R' y' U R' U' R U' R'", step: 'oll'},
  { value: "R U R' U R d' R U' R' F'", step: 'oll'},
  { value: "F R U R' U' F' U' R U2 R' U' R U' R'", step: 'oll'},
  { value: "l' U' L U' L' U L U' L' U2 l", step: 'oll'},
  { value: "r' U2 R U R' U' R U R' U r", step: 'oll'},
  { value: "r' U' R U' R' U R U' R' U2 r", step: 'oll'},
  { value: "R' F' r U' r' F r U' r' F2 R", step: 'oll'},
  { value: "F R' F' R U R U' R' U R' U' R U' R' U2 R", step: 'oll'},
  { value: "r U2 R' U' R U R' U' R U' r'", step: 'oll'},
  { value: "r U R' U R U' R' U R U2 r'", step: 'oll'},
  { value: "R' U' F' U F R U2 U' r U R' U' r' F R F'", step: 'oll'},
  { value: "r U' U2 R' U R U' R' U R U2 r'", step: 'oll'},
  { value: "r U R' U R U2 R' U U' R U R' U R U2 r'", step: 'oll'},
  { value: "R' F R U R U' R2 F' R2 U' R' U R U R'", step: 'oll'},
  { value: "F U' R2 D R' U2 R D' R2 U F'", step: 'oll'},
  { value: "R' F U R U' R2 F' R2 U R' U' R", step: 'oll'},
  { value: "U' R' F R U R U' R2 F' R2 U' R' U R U R'", step: 'oll'},
  { value: "r U2 R' U' r' R2 U R' U' r U' r'", step: 'oll'},
  { value: "r U r' U R U' R' U R U' R' r U' r'", step: 'oll'},
  { value: "F R U R' U' F' r U R' U' r' F R F'", step: 'oll'},
  { value: "F R U R' U' F' U2 l' U' L U l F' L' F", step: 'oll'},
  { value: "R U R' U' M' U R U' r'", step: 'oll'},
  { value: "R U R' U' r R' U R U' r'", step: 'oll'},
  { value: "R' U' R U M U' R' U r", step: 'oll'},
  { value: "R U R' M' r' R U' M' U R U' r'", step: 'oll'},
];

export const rawPLLalgs: LastLayerAlg[] = [
  { value: "x R' U R' D2 R U' R' D2 R2 x'", step: 'pll'},
  { value: "x' R2 D2 R' U' R D2 R' U R' x", step: 'pll'},
  { value: "R' D' R U' R' D R U' R' D' R U2 R' D R", step: 'pll'},
  { value: "R U R' F' r U R' U' r' F R2 U' R'", step: 'pll'},
  { value: "R' D' R U' R' D R U2 R' D' R U' R' D R", step: 'pll'},
  { value: "x R2 D2 R U R' D2 R U' R x'", step: 'pll'},
  { value: "x' R U' R D2 R' U R D2 R2 x", step: 'pll'},
  { value: "x L U' L D2 L' U L D2 L2 x'", step: 'pll'},
  { value: "R' D' R U2 R' D R U R' D' R U R' D R", step: 'pll'},
  { value: "l' R' D2 R U R' D2 R U' R", step: 'pll'},
  { value: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", step: 'pll'},
  { value: "R' U' R' D' R U' R' D R U R' D' R U R' D R2", step: 'pll'},
  { value: "R' U2 R' D' R U R' D R U' R' D' R U2 R' D R2", step: 'pll'},
  { value: "x' L' U L D' L' U' L D L' U' L D' L' U L D x", step: 'pll'},
  { value: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", step: 'pll'},
  { value: "R' F R f' R' F R2 U R' U' R' F' R2 U R' S", step: 'pll'},
  { value: "R' U R U' R2 F' U' F U R F R' F' R2", step: 'pll'},
  { value: "R2 U R' U R' U' R U' R2 D U' R' U R D'", step: 'pll'},
  { value: "D' R2 U R' U R' U' R U' R2 D U' R' U R", step: 'pll'},
  { value: "R2 u R' U R' U' R u' R2 F' U F", step: 'pll'},
  { value: "R U R' F' R U R' U' R' F R U' R' F R2 U' R' U' R U R' F'", step: 'pll'},
  { value: "R' U' R D' U R2 U R' U R U' R U' R2 D", step: 'pll'},
  { value: "F' U' F R2 u R' U R U' R u' R2", step: 'pll'},
  { value: "R' d' F R2 u R' U R U' R u' R2", step: 'pll'},
  { value: "D R' U' R D' U R2 U R' U R U' R U' R2", step: 'pll'},
  { value: "F' U' F R2 u R' U R U' E u U' R u' R2", step: 'pll'},
  { value: "R2 F2 R U2 R U2 R' F R U R' U' R' F R2", step: 'pll'},
  { value: "R2 U' R U' R U R' U R2 D' U R U' R' D", step: 'pll'},
  { value: "L2 U' L U' L U L' U L2 D' U L U' L' D", step: 'pll'},
  { value: "R2 F2 R U2 R U2 R' F R U R2 R U' R' F R2", step: 'pll'},
  { value: "R2 F2 R U2 R U2 U U' R' F R U R' U' R' F R2", step: 'pll'},
  { value: "R U R' D U' R2 U' R U' R' U R' U R2 D'", step: 'pll'},
  { value: "D' R U R' D U' R2 U' R U' R' U R' U R2", step: 'pll'},
  { value: "R U R' y' R2 u' R U' R' U R' u R2", step: 'pll'},
  { value: "M2 U M2 U2 M2 U M2", step: 'pll'},
  { value: "M2 U' M2 U2 M2 U' M2", step: 'pll'},
  { value: "M2 U2 M2 U M2 U2 M2", step: 'pll'},
  { value: "R' U L' U2 R U' R' U2 R L", step: 'pll'},
  { value: "L' U' L F L' U' L U L F' L2 U L", step: 'pll'},
  { value: "x R2 F R F' R U2 r' U r U2 x'", step: 'pll'},
  { value: "L' U R' U2 L U' L' U2 L R", step: 'pll'},
  { value: "R U R' F' R U R' U' R' F R2 U' R'", step: 'pll'},
  { value: "R U R2 F' R U R U' R' F R U' R'", step: 'pll'},
  { value: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'", step: 'pll'},
  { value: "R' U R U' R' F' U' F R U R' F R' F' R U' R", step: 'pll'},
  { value: "R' U R U' R' F' U' F R U R' U' R U' f R f'", step: 'pll'},
  { value: "r' D' F r U' r' F' D r2 U r' U' r' F r F'", step: 'pll'},
  { value: "R' U L' U2 R U' L R' U L' U2 R U' r", step: 'pll'},
  { value: "R' U L' U2 l F' M' U L' U2 R U' L", step: 'pll'},
  { value: "R U' R' U' R U R D R' U' R D' R' U2 R'", step: 'pll'},
  { value: "R U' R' U' R U R' U R' D' R U' R' D R2 U R'", step: 'pll'},
  { value: "R U' R2 D' R U R' D R U' R U' R' U R U R'", step: 'pll'},
  { value: "R U R' F' R U2 R' U2 R' F R U R U2 R'", step: 'pll'},
  { value: "R' U2 R' D' R U' R' D R U R U' R' U' R", step: 'pll'},
  { value: "R' U2 R U2 R' F R U R' U' R' F' R2", step: 'pll'},
  { value: "R2 F R U R U' R' F' R U2 R' U2 R", step: 'pll'},
  { value: "R' U R U R' U' R' D' R U R' D R U2 R", step: 'pll'},
  { value: "R U R' U' R' F R2 U' R' U' R U R' F'", step: 'pll'},
  { value: "R U R' U' R' F R2 U' R' U F' L' U L", step: 'pll'},
  { value: "L' U' L U L F' L2 U L U L' U' L F", step: 'pll'},
  { value: "R U R' U R' U' R2 U' R' U R' U R", step: 'pll'},
  { value: "M2 U M U2 M' U M2", step: 'pll'},
  { value: "R U' R U R U R U' R' U' R2", step: 'pll'},
  { value: "R2 U' R' U' R U R U R U' R", step: 'pll'},
  { value: "M2 U M' U2 M U M2", step: 'pll'},
  { value: "R' U R' U' R3 U' R' U R U R2", step: 'pll'},
  { value: "M2 U' M U2 M' U' M2", step: 'pll'},
  { value: "R2 U R U R' U' R3 U' R' U R'", step: 'pll'},
  { value: "R2 U R U R' U' R' U' R' U R'", step: 'pll'},
  { value: "R' U R' U' R' U' R' U R U R2", step: 'pll'},
  { value: "R' U R' d' R' F' R2 U' R' U R' F R F", step: 'pll'},
  { value: "R' U R' U' R D' R' D R' D' U R2 U' R2 D R2", step: 'pll'},
  { value: "L' U L' y' U' R' F' R2 U' R' U R' F R F", step: 'pll'},
  { value: "R' U R' d' R' F' R2 U' R' U R' F R F d", step: 'pll'},
  { value: "R' U R' d' x R' F R' F' R2 U' R' U l F", step: 'pll'},
  { value: "F R U' R' U' R U R' F' R U R' U' R' F R F'", step: 'pll'},
  { value: "B' R B R' U' R' U R2 U R' U' R' F R F'", step: 'pll'},
  { value: "F' L' U L U L' U' L F L' U' L U L F' L' F", step: 'pll'},
  { value: "F R' F R2 U' R' U' R U R' F' R U R' U' F'", step: 'pll'},
  { value: "M' U' M2 U' M2 U' M' U2 M2", step: 'pll'},
  { value: "M2 U M2 U M' U2 M2 U2 M'", step: 'pll'},
  { value: "R' U' R U' R U R U' R' U R U R2 U' R'", step: 'pll'},
  { value: "M' U M2 U M2 U M' U2 M2", step: 'pll'},
  { value: "M' U2 M2 U2 M' U M2 U M2", step: 'pll'},
];