//todo: get a text file I can just paste in all the algs into, and then a script to parse them into this

export interface RawAlg {
  value: string;
  name?: string;
  step?: string;
  allowedAngles?: string[];
}

export const rawAlgs: RawAlg[] = [ 
  { value: "R U R' U' R' F R2 U' R' U' R U R' F'", name: "T", step: "pll" },
  { value: "F R U R' U' F'", name: "45", step: "oll" },
  { value: "R U R'", name: "", step: "f2l" },
  { value: "R U2 R'", name: "", step: "f2l" },
  { value: "R U' R'", name: "", step: "f2l" },
  { value: "f R' f'", name: "", step: "f2l" },
  { value: "L U' L'", name: "", step: "f2l" },
  { value: "F U' F'", name: "", step: "f2l" },
  { value: "L U2 L'", name: "", step: "f2l" },
  { value: "R U' R'", name: "", step: "f2l" },
  { value: "r U' R' U R U r' U", name: "", step: "f2l" },
  { value: "R' U' R U R' U2' R", name: "", step: "f2l" },
  { value: "R' U' R U2 R' U R", name: "", step: "f2l" },
  { value: "R' U' R U R' U2' R", name: "", step: "f2l" },
  { value: "f' U' L' U L2 f", name: "", step: "f2l" },
  { value: "L' U' L U2' L' U L", name: "", step: "f2l" },
  { value: "R U R' U2 R U' R'", name: "", step: "f2l" },
  { value: "R' F R U R' U' F' R ", name: "", step: "f2l" },
  { value: "L U L' U' L U2 L'", name: "", step: "f2l" },
  { value: "F U R U' R' U F'", name: "", step: "f2l" },
  { value: "F R U R' U2 F'", name: "", step: "f2l" },
  { value: "R U2 R' U' R U R'", name: "", step: "f2l" },
  { value: "R U2' R' U' R U R'", name: "", step: "f2l" },
  { value: "L U2 L' U' L U L'", name: "", step: "f2l" },
  { value: "L F' L' F L' U L U' L' U L ", name: "", step: "f2l" },
  { value: "R U2 R' U' R U R'", name: "", step: "f2l" },
  { value: "R U R' U R U' R' ", name: "", step: "f2l" },
  { value: "R B' R B R2'", name: "", step: "f2l" },
  { value: "R B U2' B' R'", name: "", step: "f2l" },
  { value: "R U R2' F R F'", name: "", step: "f2l" },
  { value: "r' U r U2' r' U' r", name: "", step: "f2l" },
  { value: "f U R U' R f'", name: "", step: "f2l" },
  { value: "L U' L' U2 L U L'", name: "", step: "f2l" },
  { value: "r U' r B r2'", name: "", step: "f2l" },
  { value: "F R U2 R' F' ", name: "", step: "f2l" },
  { value: "L' U L", name: "", step: "f2l" },
  { value: "F' U F", name: "", step: "f2l" },
  { value: "F R' F' R", name: "", step: "f2l" },
  { value: "F R' F' R2 U' R'", name: "", step: "f2l" },
  { value: "R' U2 R", name: "", step: "f2l" },
  { value: "R' U R", name: "", step: "f2l" },
  { value: "f' L f", name: "", step: "f2l" },
  { value: "L' U L", name: "", step: "f2l" },
  { value: "L' U L", name: "", step: "f2l" },
  { value: "r' U2 R2 U R2' U r", name: "", step: "f2l" },
  { value: "R' U2' R U R' U2' R", name: "", step: "f2l" },
  { value: "F' U' L' U2 L U' F", name: "", step: "f2l" },
  { value: "R' U2' R U R' U2' R", name: "", step: "f2l" },
  { value: "R' U2' R U R' U2' R", name: "", step: "f2l" },
  { value: "R' F2 r2 B r2 F R", name: "", step: "f2l" },
  { value: "L' U2 L U2' L' U L", name: "", step: "f2l" },
  { value: "R U' R' U R U R' U'", name: "", step: "f2l" },
  { value: "d' R U' R' U R U R' U'", name: "", step: "f2l" },
  { value: "R' U' R U' R' U R f R f'", name: "", step: "f2l" },
  { value: "M U R' U' R U R' U2' r", name: "", step: "f2l" },
  { value: "F U R U' R' S R f'", name: "", step: "f2l" },
  { value: "L U' L' U L U L'", name: "", step: "f2l" },
  { value: "d' L U' L' U L U L'", name: "", step: "f2l" },
  { value: "F R U' R' U R U2 R' F'", name: "", step: "f2l" },
  { value: "F U M' U R U' r' F'", name: "", step: "f2l" },
  { value: "R' F R2 U2' R2' F' R2 U2' R'", name: "", step: "f2l" },
  { value: "R U2' R' U2 R U' R' U", name: "", step: "f2l" },
  { value: "r U2 R2 U' R2 U' r' U", name: "", step: "f2l" },
  { value: "F R U R2' U' R F'", name: "", step: "f2l" },
  { value: "L U2 L' U' L U2 L'", name: "", step: "f2l" },
  { value: "F U R U2' R' U F'", name: "", step: "f2l" },
  { value: "F U2 R U' R' U F'", name: "", step: "f2l" },
  { value: "L' U L U' L' U' L ", name: "", step: "f2l" },
  { value: "R U' R' U R' F R F' R U R'", name: "", step: "f2l" },
  { value: "F' L' U L U' L' U2 L F", name: "", step: "f2l" },
  { value: "R' U R U' R' U' R", name: "", step: "f2l" },
  { value: "R' U R U' R' U' R ", name: "", step: "f2l" },
  { value: "L' U L U' L' U' L ", name: "", step: "f2l" },
  { value: "R' U2 R U R' U' R ", name: "", step: "f2l" },
  { value: "R' U2 R U R' U' R", name: "", step: "f2l" },
  { value: "R' U2' R U R' U' R ", name: "", step: "f2l" },
  { value: "L' U2 L U L' U' L", name: "", step: "f2l" },
  { value: "r U' r' U2 r U r' ", name: "", step: "f2l" },
  { value: "F' L' U2 L F", name: "", step: "f2l" },
  { value: "R' F R' F' R2", name: "", step: "f2l" },
  { value: "r' U r' F' R2", name: "", step: "f2l" },
  { value: "R' F R' F' R2 ", name: "", step: "f2l" },
  { value: "R' F' U2' F R", name: "", step: "f2l" },
  { value: "l U' l' U2 l U l' ", name: "", step: "f2l" },
  { value: "L' U' L U' L' U L ", name: "", step: "f2l" },
  { value: "r' U r' F' r2", name: "", step: "f2l" },
  { value: "F' U' F", name: "", step: "f2l" },
  { value: "L' U' L", name: "", step: "f2l" },
  { value: "R' U' R", name: "", step: "f2l" },
  { value: "R' U' R", name: "", step: "f2l" },
  { value: "f' L' f", name: "", step: "f2l" },
  { value: "R' U' R", name: "", step: "f2l" },
  { value: "L' U' L U", name: "", step: "f2l" },
  { value: "R U R' U R U R'", name: "", step: "f2l" },
  { value: "R' U R U' f R f'", name: "", step: "f2l" },
  { value: "R2' U' F' U F R2", name: "", step: "f2l" },
  { value: "R U R' U R U R'", name: "", step: "f2l" },
  { value: "L U' L' U' L U L'", name: "", step: "f2l" },
  { value: "F U' R U R' U2' F'", name: "", step: "f2l" },
  { value: "R U' R' U2 F' U' F U", name: "", step: "f2l" },
  { value: "F' U2 L' U' L U' F", name: "", step: "f2l" },
  { value: "R U' B U' B' U2' R'", name: "", step: "f2l" },
  { value: "F U R U' R' F' R U R'", name: "", step: "f2l" },
  { value: "M' U R U' r' U' R U R'", name: "", step: "f2l" },
  { value: "f R' f' U2 R' U' R", name: "", step: "f2l" },
  { value: "f R' U R' U' R2 f'", name: "", step: "f2l" },
  { value: "F R' F' R U2' R' U' R2 U' R'", name: "", step: "f2l" },
  { value: "R' U' R U R D R' U' R D' R'", name: "", step: "f2l" },
  { value: "S' R' U' R S R' U2' R", name: "", step: "f2l" },
  { value: "L U' L' y U2 R' U' R", name: "", step: "f2l" },
  { value: "F U' R U' R' U2 F'", name: "", step: "f2l" },
  { value: "R U' R' U F' U' F", name: "", step: "f2l" },
  { value: "R2' U f R' f' R2", name: "", step: "f2l" },
  { value: "R' U' R S R' S' R' U R", name: "", step: "f2l" },
  { value: "R' U R U R' U' R", name: "", step: "f2l" },
  { value: "R' U' R U' R' U' R", name: "", step: "f2l" },
  { value: "U2' L' U L U L' U' L", name: "", step: "f2l" },
  { value: "l' U L U L' U' l ", name: "", step: "f2l" },
  { value: "R' F r U r' F' R ", name: "", step: "f2l" },
  { value: "F U R U' R' U2 F'", name: "", step: "f2l" },
  { value: "R U2 R' U R U R' U R U' R'", name: "", step: "f2l" },
  { value: "R' D' R U' R' D R U R U' R' ", name: "", step: "f2l" },
  { value: "R' F R F' U R U R'", name: "", step: "f2l" },
  { value: "S' R U R' S R U2' R'", name: "", step: "f2l" },
  { value: "R2' F R F' R U2' R' U R", name: "", step: "f2l" },
  { value: "R' U R U2' f R f'", name: "", step: "f2l" },
  { value: "f R2' U R U' R f'", name: "", step: "f2l" },
  { value: "R' U' S' R U2' R' S R", name: "", step: "f2l" },
  { value: "L U2 L' U L U L' U L U' L' ", name: "", step: "f2l" },
  { value: "L' U L U2 F U F'", name: "", step: "f2l" },
  { value: "R U2 R' U R U' R'", name: "", step: "f2l" },
  { value: "R U2' R2' F R F'", name: "", step: "f2l" },
  { value: "R U2' R' U R U' R'", name: "", step: "f2l" },
  { value: "L U2 L' U L U' L' ", name: "", step: "f2l" },
  { value: "r B U' r B r2'", name: "", step: "f2l" },
  { value: "R U2' R' U R U' R'", name: "", step: "f2l" },
  { value: "F U R' F R F2'", name: "", step: "f2l" },
  { value: "F U R' F R F2'", name: "", step: "f2l" },
  { value: "R U' R2' D' R U2 R' D R", name: "", step: "f2l" },
  { value: "R U' R' U' R U' R' U R U' R'", name: "", step: "f2l" },
  { value: "F R' F' R U R U R' U R' F R' F' R2 U' R' U R ", name: "", step: "f2l" },
  { value: "R' F' r U' r' F2 U' R", name: "", step: "f2l" },
  { value: "R' F' U' F2 R' F' R2", name: "", step: "f2l" },
  { value: "L U' L' U' L U' L' U L U' L' U", name: "", step: "f2l" },
  { value: "F U' R U R' U R U2' R' F'", name: "", step: "f2l" },
  { value: "R U R'", name: "", step: "f2l" },
  { value: "f R f'", name: "", step: "f2l" },
  { value: "R U R'", name: "", step: "f2l" },
  { value: "L U L'", name: "", step: "f2l" },
  { value: "L U L'", name: "", step: "f2l" },
  { value: "F U F'", name: "", step: "f2l" },
  { value: "L U L'", name: "", step: "f2l" },
  { value: "R U R'", name: "", step: "f2l" },
  { value: "R U' R' U R U' R' U2 R U' R'", name: "", step: "f2l" },
  { value: "R' U2 R U' f R f'", name: "", step: "f2l" },
  { value: "L' U2 L2 U L2 U L", name: "", step: "f2l" },
  { value: "F U' R U2 R' U2 F'", name: "", step: "f2l" },
  { value: "R U2 R' U F' U' F", name: "", step: "f2l" },
  { value: "R U2' R2' U' R2 U' R'", name: "", step: "f2l" },
  { value: "R U2' R2' U' R2 U' R'", name: "", step: "f2l" },
  { value: "L U2 L2 U' L2 U' L'", name: "", step: "f2l" },
  { value: "L' U2 L U' L' U L U'", name: "", step: "f2l" },
  { value: "R U' R2' F R F' R U' R'", name: "", step: "f2l" },
  { value: "R' U' F R' F' R2", name: "", step: "f2l" },
  { value: "R U' R2' F R F' U' R' F R F'", name: "", step: "f2l" },
  { value: "R' U2 R U' R' U R ", name: "", step: "f2l" },
  { value: "R' U2 R U' R' U R ", name: "", step: "f2l" },
  { value: "L' U2 L2 F' L' F", name: "", step: "f2l" },
  { value: "F U R U' R' F' R U' R'", name: "", step: "f2l" },
  { value: "R U' R2' F R F' R U' R'", name: "", step: "f2l" },
  { value: "F R' F' D' R U R' D R ", name: "", step: "f2l" },
  { value: "R U R' U R U2' R2' U R", name: "", step: "f2l" },
  { value: "r U R' U R U2 B r' ", name: "", step: "f2l" },
  { value: "F U' R U2 R' U R U2 R' F' ", name: "", step: "f2l" },
]