/**
 * Generate basic y-move algorithms as AlgCompiler input records (ExactAlg shape).
 *
 * Each alg has the form:  trigger_1 y AUF trigger_2
 *
 * A trigger is `X U* X'` where X is a single face move (with optional prime) and
 * the middle U move is U, U' or U2.
 *   - trigger_1 is an R or L trigger.
 *   - trigger_2 is an R, L or F trigger.
 * The middle AUF is optional and may be U, U', U2 or nothing. The leading AUF is
 * left off and regenerated by the AlgCompiler, which adds every leading AUF.
 */

import * as fs from 'fs';
import * as path from 'path';
import { SimpleCube } from '../composables/recon/SimpleCube';
import { SimpleCubeInterpreter } from '../composables/recon/SimpleCubeInterpreter';
import { reverseMove } from '../composables/recon/transformHTML';

interface YMoveAlg {
  new: boolean;
  value: string;
  step: string;
  add_y: boolean;
}

const trigger1Faces = ['R', 'L'] as const;
const trigger2Faces = ['R', 'L', 'F'] as const;
const uMoves = ['U', "U'", 'U2'] as const;
const aufs = ['', 'U', "U'", 'U2'] as const;
const yMoves = ['y', "y'"] as const;

function invert(move: string): string {
  return move.endsWith("'") ? move.slice(0, -1) : move + "'";
}

interface Trigger {
  face: string;
  value: string;
}

function triggers(faces: readonly string[]): Trigger[] {
  const result: Trigger[] = [];
  for (const face of faces) {
    for (const dir of ['', "'"]) {
      const open = face + dir;
      const close = invert(open);
      for (const uMove of uMoves) {
        result.push({ face, value: [open, uMove, close].join(' ') });
      }
    }
  }
  return result;
}

const SOLVED_HASH = 'abcdefghijklehkbnqtwabcdef';

const edgeCharToSlot: { [char: string]: number } = {
  i: 8, u: 8,   // FR
  j: 9, v: 9,   // FL
  k: 10, w: 10, // BR
  l: 11, x: 11, // BL
};

const crossEdgeIndices = [4, 5, 6, 7];

const f2lSlots = [
  { edge: 8, corner: 16 },  // FR
  { edge: 10, corner: 19 }, // BR
  { edge: 9, corner: 17 },  // FL
  { edge: 11, corner: 18 }, // BL
];

function invertAlg(value: string): string[] {
  return value.split(' ').map(reverseMove).reverse();
}

function hashOf(moves: string[]): string {
  const cube = new SimpleCube();
  const interpreter = new SimpleCubeInterpreter();
  interpreter.getStepsCompleted(cube.getCubeState(moves));
  return interpreter.getCurrentState()?.hash || SOLVED_HASH;
}

function isUnsolved(hash: string, slot: { edge: number; corner: number }): boolean {
  return hash[slot.edge] !== SOLVED_HASH[slot.edge] || hash[slot.corner] !== SOLVED_HASH[slot.corner];
}

function solvedEdgeStartsInDifferentSlot(value: string): boolean {
  const moves = value.split(' ');
  const inverseMoves = invertAlg(value);
  const startHash = hashOf(inverseMoves);

  const crossSolved = crossEdgeIndices.every(i => startHash[i] === SOLVED_HASH[i]);
  if (!crossSolved) return false;

  const disturbedSlots = f2lSlots.filter(s => isUnsolved(startHash, s));
  if (disturbedSlots.length === 0) return false;

  const beforeLastHash = hashOf([...inverseMoves, ...moves.slice(0, -1)]);
  const targetSlots = disturbedSlots.filter(s => isUnsolved(beforeLastHash, s));
  if (targetSlots.length !== 1) return false;

  const targetSlot = targetSlots[0];
  const startSlot = edgeCharToSlot[startHash[targetSlot.edge]];
  if (startSlot === undefined) return false;

  return startSlot !== targetSlot.edge;
}

const inefficientEndings = [
  "U2 L' U2 L",
  "U2 L U2 L'",
  "U2 R' U2 R",
  "U2 R U2 R'",
  "U' L' U2 L",
  "U L U2 L'",
  "U R U2 R'",
  "U' R' U2 R",
  "U' R U' R'",
  "U R' U R",
  "U L' U L",
  "U' L U' L'",
];

function hasInefficientEnding(value: string): boolean {
  return inefficientEndings.some(ending => value.endsWith(ending));
}

function isPointlessPair(
  trigger1Face: string,
  yMove: string,
  trigger2Face: string,
): boolean {
  if (trigger2Face !== 'F') return false;
  return (
    (yMove === 'y' && trigger1Face === 'R') ||
    (yMove === "y'" && trigger1Face === 'L')
  );
}

function generateAlgs(): YMoveAlg[] {
  const algs: YMoveAlg[] = [];

  const trigger1s = triggers(trigger1Faces);
  const trigger2s = triggers(trigger2Faces);

  for (const trigger1 of trigger1s) {
    for (const yMove of yMoves) {
      for (const auf2 of aufs) {
        for (const trigger2 of trigger2s) {
          if (isPointlessPair(trigger1.face, yMove, trigger2.face)) continue;
          const value = [trigger1.value, yMove, auf2, trigger2.value]
            .filter(Boolean)
            .join(' ');
          if (hasInefficientEnding(value)) continue;
          if (!solvedEdgeStartsInDifferentSlot(value)) continue;
          algs.push({
            new: true,
            value,
            step: 'f2l',
            add_y: false,
          });
        }
      }
    }
  }

  return algs;
}

function main() {
  const algs = generateAlgs();

  const outputPath = path.join(__dirname, '..', 'y-move-algs.json');
  fs.writeFileSync(outputPath, JSON.stringify(algs, null, 2), 'utf-8');

  console.error(`Wrote ${algs.length} y-move algs to ${outputPath}`);
}

main();
